// src/admin/drawers/AddJurorDrawer.jsx
// Drawer: add a new juror to the current period.
// PIN is auto-generated by the backend.
//
// Props:
//   open         — boolean
//   onClose      — () => void
//   onSave       — ({ name, affiliation, email }) => Promise<void>
//   periodName   — string | null  — shown in subtitle
//   error        — string | null

import { useState, useEffect } from "react";
import { AlertCircle, Info, UserPlus, X } from "lucide-react";
import Drawer from "@/shared/ui/Drawer";
import FbAlert from "@/shared/ui/FbAlert";
import AsyncButtonContent from "@/shared/ui/AsyncButtonContent";
import useShakeOnError from "@/shared/hooks/useShakeOnError";

const EMPTY = { name: "", affiliation: "", email: "" };

export default function AddJurorDrawer({ open, onClose, onSave, periodName, error }) {
  const [form, setForm] = useState(EMPTY);
  const [touched, setTouched] = useState({});
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState("");

  useEffect(() => {
    if (open) { setForm(EMPTY); setTouched({}); setSaveError(""); setSaving(false); }
  }, [open]);

  const set = (key, val) => setForm((f) => ({ ...f, [key]: val }));
  const touch = (key) => setTouched((t) => ({ ...t, [key]: true }));

  const handleSave = async () => {
    setTouched({ name: true, affiliation: true });
    if (!form.name.trim() || !form.affiliation.trim()) return;
    setSaveError("");
    setSaving(true);
    try {
      await onSave?.({
        name: form.name.trim(),
        affiliation: form.affiliation.trim(),
        email: form.email.trim() || null,
      });
      onClose();
    } catch (e) {
      setSaveError("Failed to add juror. Please try again.");
    } finally {
      setSaving(false);
    }
  };

  const displayError = saveError || error;
  const saveBtnRef = useShakeOnError(displayError);
  const subtitle = periodName ? `Register a new evaluator for ${periodName}.` : "Register a new evaluator.";

  return (
    <Drawer open={open} onClose={onClose}>
      <div className="fs-drawer-header">
        <div className="fs-drawer-header-row">
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <div className="fs-icon identity" aria-hidden="true">
              <UserPlus size={18} />
            </div>
            <div className="fs-title-group">
              <div className="fs-title">Add Juror</div>
              <div className="fs-subtitle">{subtitle}</div>
            </div>
          </div>
          <button className="fs-close" type="button" onClick={onClose} aria-label="Close">
            <X size={16} strokeWidth={2.5} />
          </button>
        </div>
      </div>

      <div className="fs-drawer-body">
        {displayError && (
          <FbAlert variant="danger" style={{ marginBottom: 14 }} data-testid="jurors-drawer-error">{displayError}</FbAlert>
        )}

        {/* Identity section */}
        <div className="fs-section">
          <div className="fs-section-header">
            <span className="fs-section-title">Identity</span>
          </div>

          <div className="fs-field">
            <label className="fs-field-label">
              Full Name <span className="fs-field-req">*</span>
            </label>
            <input
              className={`fs-input${touched.name && !form.name.trim() ? " error" : ""}`}
              type="text"
              placeholder="Prof. Dr. Sevgi Kahraman"
              value={form.name}
              onChange={(e) => set("name", e.target.value)}
              onBlur={() => touch("name")}
              disabled={saving}
              autoFocus
              data-testid="jurors-drawer-name"
            />
            {touched.name && !form.name.trim() && (
              <p className="crt-field-error"><AlertCircle size={12} strokeWidth={2} />Full name is required.</p>
            )}
          </div>

          <div className="fs-field">
            <label className="fs-field-label">
              Affiliation <span className="fs-field-req">*</span>
            </label>
            <input
              className={`fs-input${touched.affiliation && !form.affiliation.trim() ? " error" : ""}`}
              type="text"
              placeholder="TED University"
              value={form.affiliation}
              onChange={(e) => set("affiliation", e.target.value)}
              onBlur={() => touch("affiliation")}
              disabled={saving}
              data-testid="jurors-drawer-affiliation"
            />
            {touched.affiliation && !form.affiliation.trim() ? (
              <p className="crt-field-error"><AlertCircle size={12} strokeWidth={2} />Affiliation is required.</p>
            ) : (
              <div className="fs-field-helper hint">
                <Info size={12} />
                University, company or research institution.
              </div>
            )}
          </div>

          <div className="fs-field">
            <label className="fs-field-label">
              Email <span className="fs-field-opt">(optional)</span>
            </label>
            <input
              className="fs-input"
              type="email"
              placeholder="juror@university.edu"
              value={form.email}
              onChange={(e) => set("email", e.target.value)}
              disabled={saving}
              autoComplete="off"
              spellCheck="false"
              data-testid="jurors-drawer-email"
            />
            <div style={{ marginTop: 5, display: "flex", alignItems: "center", gap: 5, color: "var(--text-tertiary)", fontSize: 11 }}>
              <Info size={11} strokeWidth={2} />
              Used to send PIN and evaluation QR code via email.
            </div>
          </div>
        </div>

        {/* Access section */}
        <div className="fs-section">
          <div className="fs-section-header">
            <span className="fs-section-title">Access</span>
          </div>
          <FbAlert variant="info" title="PIN auto-generated" style={{ marginBottom: 0 }}>
            A unique 4-digit PIN will be assigned automatically. You can reset it later from the juror profile.
          </FbAlert>
        </div>
      </div>

      <div className="fs-drawer-footer">
        <button
          className="fs-btn fs-btn-secondary"
          type="button"
          onClick={onClose}
          disabled={saving}
          data-testid="jurors-drawer-cancel"
        >
          Cancel
        </button>
        <button
          ref={saveBtnRef}
          className="fs-btn fs-btn-primary"
          type="button"
          onClick={handleSave}
          disabled={saving || !form.name.trim() || !form.affiliation.trim()}
          data-testid="jurors-drawer-save"
        >
          <span className="btn-loading-content">
            <AsyncButtonContent loading={saving} loadingText="Creating…">Add Juror</AsyncButtonContent>
          </span>
        </button>
      </div>
    </Drawer>
  );
}
