// src/admin/drawers/AddJurorDrawer.jsx
// Drawer: add a new juror to the current period.
// PIN is auto-generated by the backend.
//
// Props:
//   open       — boolean
//   onClose    — () => void
//   onSave     — ({ name, affiliation, email }) => Promise<void>
//   error      — string | null

import { useState, useEffect } from "react";
import Drawer from "@/shared/ui/Drawer";

const EMPTY = { name: "", affiliation: "", email: "" };

export default function AddJurorDrawer({ open, onClose, onSave, error }) {
  const [form, setForm] = useState(EMPTY);
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState("");

  useEffect(() => {
    if (open) { setForm(EMPTY); setSaveError(""); setSaving(false); }
  }, [open]);

  const set = (key, val) => setForm((f) => ({ ...f, [key]: val }));

  const handleSave = async () => {
    setSaveError("");
    setSaving(true);
    try {
      await onSave?.({
        name: form.name.trim(),
        affiliation: form.affiliation.trim(),
        email: form.email.trim() || null,
      });
      onClose();
    } catch (e) {
      setSaveError(e?.message || "Something went wrong.");
    } finally {
      setSaving(false);
    }
  };

  const displayError = saveError || error;

  return (
    <Drawer open={open} onClose={onClose}>
      <div className="fs-drawer-header">
        <div className="fs-drawer-header-row">
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <span className="fs-icon accent" aria-hidden="true">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></svg>
            </span>
            <div className="fs-title-group">
              <div className="fs-title">Add Juror</div>
              <div className="fs-subtitle">A PIN will be auto-generated on creation</div>
            </div>
          </div>
          <button className="fs-close" type="button" onClick={onClose} aria-label="Close">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><path d="M18 6 6 18M6 6l12 12"/></svg>
          </button>
        </div>
      </div>

      <div className="fs-drawer-body">
        {displayError && (
          <div className="fs-alert danger" style={{ marginBottom: 14 }}>
            <div className="fs-alert-body">{displayError}</div>
          </div>
        )}

        <div className="fs-alert info" style={{ marginBottom: 14 }}>
          <div className="fs-alert-icon">
            <svg viewBox="0 0 24 24" fill="none" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 16v-4M12 8h.01"/></svg>
          </div>
          <div className="fs-alert-body">
            <div className="fs-alert-title">PIN auto-generated</div>
            <div className="fs-alert-desc">A 4-digit PIN will be created automatically. The juror can view it on first login.</div>
          </div>
        </div>

        <div className="fs-field">
          <label className="fs-field-label">
            Full Name <span className="fs-field-req">*</span>
          </label>
          <input
            className="fs-input"
            type="text"
            placeholder="Juror's full name"
            value={form.name}
            onChange={(e) => set("name", e.target.value)}
            disabled={saving}
          />
        </div>

        <div className="fs-field">
          <label className="fs-field-label">
            Affiliation <span className="fs-field-req">*</span>
          </label>
          <input
            className="fs-input"
            type="text"
            placeholder="University or organization"
            value={form.affiliation}
            onChange={(e) => set("affiliation", e.target.value)}
            disabled={saving}
          />
        </div>

        <div className="fs-field">
          <label className="fs-field-label">
            Email <span className="fs-field-opt">(optional)</span>
          </label>
          <input
            className="fs-input"
            type="email"
            placeholder="juror@example.com"
            value={form.email}
            onChange={(e) => set("email", e.target.value)}
            disabled={saving}
          />
        </div>
      </div>

      <div className="fs-drawer-footer">
        <button className="fs-btn fs-btn-secondary" type="button" onClick={onClose} disabled={saving}>
          Cancel
        </button>
        <button
          className="fs-btn fs-btn-primary"
          type="button"
          onClick={handleSave}
          disabled={saving || !form.name.trim() || !form.affiliation.trim()}
        >
          {saving ? "Creating…" : "Add Juror"}
        </button>
      </div>
    </Drawer>
  );
}
