// src/admin/drawers/AddJurorDrawer.jsx
// Drawer: add a new juror to the current period.
// PIN is auto-generated by the backend.
//
// Props:
//   open         — boolean
//   onClose      — () => void
//   onSave       — ({ name, affiliation, email }) => Promise<void>
//   periodName   — string | null  — shown in subtitle
//   error        — string | null

import { useState, useEffect } from "react";
import { AlertCircle, Info, UserPlus, X } from "lucide-react";
import Drawer from "@/shared/ui/Drawer";
import AsyncButtonContent from "@/shared/ui/AsyncButtonContent";
import useShakeOnError from "@/shared/hooks/useShakeOnError";

const EMPTY = { name: "", affiliation: "", email: "" };

export default function AddJurorDrawer({ open, onClose, onSave, periodName, error }) {
  const [form, setForm] = useState(EMPTY);
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState("");

  useEffect(() => {
    if (open) { setForm(EMPTY); setSaveError(""); setSaving(false); }
  }, [open]);

  const set = (key, val) => setForm((f) => ({ ...f, [key]: val }));

  const handleSave = async () => {
    setSaveError("");
    setSaving(true);
    try {
      await onSave?.({
        name: form.name.trim(),
        affiliation: form.affiliation.trim(),
        email: form.email.trim() || null,
      });
      onClose();
    } catch (e) {
      setSaveError(e?.message || "Something went wrong.");
    } finally {
      setSaving(false);
    }
  };

  const displayError = saveError || error;
  const saveBtnRef = useShakeOnError(displayError);
  const subtitle = periodName ? `Register a new evaluator for ${periodName}.` : "Register a new evaluator.";

  return (
    <Drawer open={open} onClose={onClose}>
      <div className="fs-drawer-header">
        <div className="fs-drawer-header-row">
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <div className="fs-icon identity" aria-hidden="true">
              <UserPlus size={18} />
            </div>
            <div className="fs-title-group">
              <div className="fs-title">Add Juror</div>
              <div className="fs-subtitle">{subtitle}</div>
            </div>
          </div>
          <button className="fs-close" type="button" onClick={onClose} aria-label="Close">
            <X size={16} strokeWidth={2.5} />
          </button>
        </div>
      </div>

      <div className="fs-drawer-body">
        {displayError && (
          <div className="fs-alert danger" style={{ marginBottom: 14 }}>
            <div className="fs-alert-icon"><AlertCircle size={15} /></div>
            <div className="fs-alert-body">{displayError}</div>
          </div>
        )}

        {/* Identity section */}
        <div className="fs-section">
          <div className="fs-section-header">
            <span className="fs-section-title">Identity</span>
          </div>

          <div className="fs-field">
            <label className="fs-field-label">
              Full Name <span className="fs-field-req">*</span>
            </label>
            <input
              className="fs-input"
              type="text"
              placeholder="Prof. Dr. Sevgi Kahraman"
              value={form.name}
              onChange={(e) => set("name", e.target.value)}
              disabled={saving}
              autoFocus
            />
          </div>

          <div className="fs-field">
            <label className="fs-field-label">
              Affiliation <span className="fs-field-req">*</span>
            </label>
            <input
              className="fs-input"
              type="text"
              placeholder="TED University"
              value={form.affiliation}
              onChange={(e) => set("affiliation", e.target.value)}
              disabled={saving}
            />
            <div className="fs-field-helper hint">
              <Info size={12} />
              University, company or research institution.
            </div>
          </div>

          <div className="fs-field">
            <label className="fs-field-label">
              Email <span className="fs-field-opt">(optional)</span>
            </label>
            <input
              className="fs-input"
              type="email"
              placeholder="juror@university.edu"
              value={form.email}
              onChange={(e) => set("email", e.target.value)}
              disabled={saving}
              autoComplete="off"
              spellCheck="false"
            />
            <div style={{ marginTop: 5, display: "flex", alignItems: "center", gap: 5, color: "var(--text-tertiary)", fontSize: 11 }}>
              <Info size={11} strokeWidth={2} />
              Used to send PIN and evaluation QR code via email.
            </div>
          </div>
        </div>

        {/* Access section */}
        <div className="fs-section">
          <div className="fs-section-header">
            <span className="fs-section-title">Access</span>
          </div>
          <div className="fs-alert info" style={{ marginBottom: 0 }}>
            <div className="fs-alert-icon"><Info size={15} /></div>
            <div className="fs-alert-body">
              <div className="fs-alert-title">PIN auto-generated</div>
              <div className="fs-alert-desc">A unique 4-digit PIN will be assigned automatically. You can reset it later from the juror profile.</div>
            </div>
          </div>
        </div>
      </div>

      <div className="fs-drawer-footer">
        <button className="fs-btn fs-btn-secondary" type="button" onClick={onClose} disabled={saving}>
          Cancel
        </button>
        <button
          ref={saveBtnRef}
          className="fs-btn fs-btn-primary"
          type="button"
          onClick={handleSave}
          disabled={saving || !form.name.trim() || !form.affiliation.trim()}
        >
          <span className="btn-loading-content">
            <AsyncButtonContent loading={saving} loadingText="Creating…">Add Juror</AsyncButtonContent>
          </span>
        </button>
      </div>
    </Drawer>
  );
}
