// AUTOGENERATED — do not edit by hand.
// Regenerate with: npm run gen:db-types
// Source: Supabase project vera-prod (etxgvkvxvbyserhrugjw), schema=public
// Drift detection: scripts/check-db-types.mjs (CI gate, P0-A2)

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  public: {
    Tables: {
      admin_user_sessions: {
        Row: {
          auth_method: string | null
          browser: string | null
          country_code: string | null
          created_at: string
          device_id: string
          expires_at: string | null
          first_seen_at: string
          id: string
          ip_address: string | null
          last_activity_at: string
          os: string | null
          signed_in_at: string | null
          updated_at: string
          user_agent: string | null
          user_id: string
        }
        Insert: {
          auth_method?: string | null
          browser?: string | null
          country_code?: string | null
          created_at?: string
          device_id: string
          expires_at?: string | null
          first_seen_at?: string
          id?: string
          ip_address?: string | null
          last_activity_at?: string
          os?: string | null
          signed_in_at?: string | null
          updated_at?: string
          user_agent?: string | null
          user_id: string
        }
        Update: {
          auth_method?: string | null
          browser?: string | null
          country_code?: string | null
          created_at?: string
          device_id?: string
          expires_at?: string | null
          first_seen_at?: string
          id?: string
          ip_address?: string | null
          last_activity_at?: string
          os?: string | null
          signed_in_at?: string | null
          updated_at?: string
          user_agent?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_user_sessions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_logs: {
        Row: {
          action: string
          actor_name: string | null
          actor_type: Database["public"]["Enums"]["audit_actor_type"] | null
          category: Database["public"]["Enums"]["audit_category"] | null
          chain_seq: number
          correlation_id: string | null
          created_at: string | null
          details: Json | null
          diff: Json | null
          id: string
          ip_address: unknown
          organization_id: string | null
          resource_id: string | null
          resource_type: string | null
          row_hash: string | null
          session_id: string | null
          severity: Database["public"]["Enums"]["audit_severity"] | null
          user_agent: string | null
          user_id: string | null
        }
        Insert: {
          action: string
          actor_name?: string | null
          actor_type?: Database["public"]["Enums"]["audit_actor_type"] | null
          category?: Database["public"]["Enums"]["audit_category"] | null
          chain_seq?: number
          correlation_id?: string | null
          created_at?: string | null
          details?: Json | null
          diff?: Json | null
          id?: string
          ip_address?: unknown
          organization_id?: string | null
          resource_id?: string | null
          resource_type?: string | null
          row_hash?: string | null
          session_id?: string | null
          severity?: Database["public"]["Enums"]["audit_severity"] | null
          user_agent?: string | null
          user_id?: string | null
        }
        Update: {
          action?: string
          actor_name?: string | null
          actor_type?: Database["public"]["Enums"]["audit_actor_type"] | null
          category?: Database["public"]["Enums"]["audit_category"] | null
          chain_seq?: number
          correlation_id?: string | null
          created_at?: string | null
          details?: Json | null
          diff?: Json | null
          id?: string
          ip_address?: unknown
          organization_id?: string | null
          resource_id?: string | null
          resource_type?: string | null
          row_hash?: string | null
          session_id?: string | null
          severity?: Database["public"]["Enums"]["audit_severity"] | null
          user_agent?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_logs_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_logs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      email_verification_tokens: {
        Row: {
          consumed_at: string | null
          created_at: string | null
          email: string
          expires_at: string
          token: string
          user_id: string
        }
        Insert: {
          consumed_at?: string | null
          created_at?: string | null
          email: string
          expires_at: string
          token?: string
          user_id: string
        }
        Update: {
          consumed_at?: string | null
          created_at?: string | null
          email?: string
          expires_at?: string
          token?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "email_verification_tokens_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      entry_tokens: {
        Row: {
          created_at: string | null
          expires_at: string | null
          id: string
          is_revoked: boolean | null
          last_used_at: string | null
          period_id: string
          revoked_at: string | null
          token_hash: string
          token_plain: string | null
        }
        Insert: {
          created_at?: string | null
          expires_at?: string | null
          id?: string
          is_revoked?: boolean | null
          last_used_at?: string | null
          period_id: string
          revoked_at?: string | null
          token_hash: string
          token_plain?: string | null
        }
        Update: {
          created_at?: string | null
          expires_at?: string | null
          id?: string
          is_revoked?: boolean | null
          last_used_at?: string | null
          period_id?: string
          revoked_at?: string | null
          token_hash?: string
          token_plain?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "entry_tokens_period_id_fkey"
            columns: ["period_id"]
            isOneToOne: false
            referencedRelation: "periods"
            referencedColumns: ["id"]
          },
        ]
      }
      framework_criteria: {
        Row: {
          color: string | null
          description: string | null
          framework_id: string
          id: string
          key: string
          label: string
          max_score: number
          rubric_bands: Json | null
          sort_order: number | null
          weight: number
        }
        Insert: {
          color?: string | null
          description?: string | null
          framework_id: string
          id?: string
          key: string
          label: string
          max_score: number
          rubric_bands?: Json | null
          sort_order?: number | null
          weight: number
        }
        Update: {
          color?: string | null
          description?: string | null
          framework_id?: string
          id?: string
          key?: string
          label?: string
          max_score?: number
          rubric_bands?: Json | null
          sort_order?: number | null
          weight?: number
        }
        Relationships: [
          {
            foreignKeyName: "framework_criteria_framework_id_fkey"
            columns: ["framework_id"]
            isOneToOne: false
            referencedRelation: "frameworks"
            referencedColumns: ["id"]
          },
        ]
      }
      framework_criterion_outcome_maps: {
        Row: {
          coverage_type: string
          criterion_id: string
          framework_id: string
          id: string
          outcome_id: string
          period_id: string | null
          weight: number | null
        }
        Insert: {
          coverage_type?: string
          criterion_id: string
          framework_id: string
          id?: string
          outcome_id: string
          period_id?: string | null
          weight?: number | null
        }
        Update: {
          coverage_type?: string
          criterion_id?: string
          framework_id?: string
          id?: string
          outcome_id?: string
          period_id?: string | null
          weight?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "framework_criterion_outcome_maps_criterion_id_fkey"
            columns: ["criterion_id"]
            isOneToOne: false
            referencedRelation: "framework_criteria"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "framework_criterion_outcome_maps_framework_id_fkey"
            columns: ["framework_id"]
            isOneToOne: false
            referencedRelation: "frameworks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "framework_criterion_outcome_maps_outcome_id_fkey"
            columns: ["outcome_id"]
            isOneToOne: false
            referencedRelation: "framework_outcomes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "framework_criterion_outcome_maps_period_id_fkey"
            columns: ["period_id"]
            isOneToOne: false
            referencedRelation: "periods"
            referencedColumns: ["id"]
          },
        ]
      }
      framework_outcomes: {
        Row: {
          code: string
          created_at: string | null
          description: string | null
          framework_id: string
          id: string
          label: string
          sort_order: number | null
        }
        Insert: {
          code: string
          created_at?: string | null
          description?: string | null
          framework_id: string
          id?: string
          label: string
          sort_order?: number | null
        }
        Update: {
          code?: string
          created_at?: string | null
          description?: string | null
          framework_id?: string
          id?: string
          label?: string
          sort_order?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "framework_outcomes_framework_id_fkey"
            columns: ["framework_id"]
            isOneToOne: false
            referencedRelation: "frameworks"
            referencedColumns: ["id"]
          },
        ]
      }
      frameworks: {
        Row: {
          created_at: string | null
          default_threshold: number | null
          description: string | null
          id: string
          name: string
          organization_id: string | null
        }
        Insert: {
          created_at?: string | null
          default_threshold?: number | null
          description?: string | null
          id?: string
          name: string
          organization_id?: string | null
        }
        Update: {
          created_at?: string | null
          default_threshold?: number | null
          description?: string | null
          id?: string
          name?: string
          organization_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "frameworks_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      juror_period_auth: {
        Row: {
          created_at: string | null
          edit_enabled: boolean | null
          edit_expires_at: string | null
          edit_reason: string | null
          failed_attempts: number | null
          final_submitted_at: string | null
          is_blocked: boolean | null
          juror_id: string
          last_seen_at: string | null
          locked_at: string | null
          locked_until: string | null
          period_id: string
          pin_hash: string | null
          pin_pending_reveal: string | null
          session_expires_at: string | null
          session_token_hash: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string | null
          edit_enabled?: boolean | null
          edit_expires_at?: string | null
          edit_reason?: string | null
          failed_attempts?: number | null
          final_submitted_at?: string | null
          is_blocked?: boolean | null
          juror_id: string
          last_seen_at?: string | null
          locked_at?: string | null
          locked_until?: string | null
          period_id: string
          pin_hash?: string | null
          pin_pending_reveal?: string | null
          session_expires_at?: string | null
          session_token_hash?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string | null
          edit_enabled?: boolean | null
          edit_expires_at?: string | null
          edit_reason?: string | null
          failed_attempts?: number | null
          final_submitted_at?: string | null
          is_blocked?: boolean | null
          juror_id?: string
          last_seen_at?: string | null
          locked_at?: string | null
          locked_until?: string | null
          period_id?: string
          pin_hash?: string | null
          pin_pending_reveal?: string | null
          session_expires_at?: string | null
          session_token_hash?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "juror_period_auth_juror_id_fkey"
            columns: ["juror_id"]
            isOneToOne: false
            referencedRelation: "jurors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "juror_period_auth_period_id_fkey"
            columns: ["period_id"]
            isOneToOne: false
            referencedRelation: "periods"
            referencedColumns: ["id"]
          },
        ]
      }
      jurors: {
        Row: {
          affiliation: string
          avatar_color: string | null
          created_at: string | null
          email: string | null
          id: string
          juror_name: string
          notes: string | null
          organization_id: string
          updated_at: string | null
        }
        Insert: {
          affiliation: string
          avatar_color?: string | null
          created_at?: string | null
          email?: string | null
          id?: string
          juror_name: string
          notes?: string | null
          organization_id: string
          updated_at?: string | null
        }
        Update: {
          affiliation?: string
          avatar_color?: string | null
          created_at?: string | null
          email?: string | null
          id?: string
          juror_name?: string
          notes?: string | null
          organization_id?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "jurors_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      jury_feedback: {
        Row: {
          comment: string | null
          created_at: string
          id: string
          is_public: boolean
          juror_id: string
          period_id: string
          rating: number
        }
        Insert: {
          comment?: string | null
          created_at?: string
          id?: string
          is_public?: boolean
          juror_id: string
          period_id: string
          rating: number
        }
        Update: {
          comment?: string | null
          created_at?: string
          id?: string
          is_public?: boolean
          juror_id?: string
          period_id?: string
          rating?: number
        }
        Relationships: [
          {
            foreignKeyName: "jury_feedback_juror_id_fkey"
            columns: ["juror_id"]
            isOneToOne: false
            referencedRelation: "jurors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jury_feedback_period_id_fkey"
            columns: ["period_id"]
            isOneToOne: false
            referencedRelation: "periods"
            referencedColumns: ["id"]
          },
        ]
      }
      maintenance_mode: {
        Row: {
          activated_by: string | null
          affected_org_ids: string[] | null
          end_time: string | null
          id: number
          is_active: boolean
          message: string
          mode: string
          notify_admins: boolean
          start_time: string | null
          updated_at: string | null
        }
        Insert: {
          activated_by?: string | null
          affected_org_ids?: string[] | null
          end_time?: string | null
          id?: number
          is_active?: boolean
          message?: string
          mode?: string
          notify_admins?: boolean
          start_time?: string | null
          updated_at?: string | null
        }
        Update: {
          activated_by?: string | null
          affected_org_ids?: string[] | null
          end_time?: string | null
          id?: number
          is_active?: boolean
          message?: string
          mode?: string
          notify_admins?: boolean
          start_time?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      memberships: {
        Row: {
          created_at: string | null
          grace_ends_at: string | null
          id: string
          is_owner: boolean
          organization_id: string | null
          role: string
          status: string
          user_id: string
        }
        Insert: {
          created_at?: string | null
          grace_ends_at?: string | null
          id?: string
          is_owner?: boolean
          organization_id?: string | null
          role?: string
          status?: string
          user_id: string
        }
        Update: {
          created_at?: string | null
          grace_ends_at?: string | null
          id?: string
          is_owner?: boolean
          organization_id?: string | null
          role?: string
          status?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "memberships_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "memberships_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      org_applications: {
        Row: {
          applicant_name: string
          contact_email: string
          created_at: string | null
          id: string
          message: string | null
          organization_id: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          status: string
        }
        Insert: {
          applicant_name: string
          contact_email: string
          created_at?: string | null
          id?: string
          message?: string | null
          organization_id?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
        }
        Update: {
          applicant_name?: string
          contact_email?: string
          created_at?: string | null
          id?: string
          message?: string | null
          organization_id?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "org_applications_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "org_applications_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      organizations: {
        Row: {
          code: string
          contact_email: string | null
          created_at: string | null
          id: string
          name: string
          settings: Json
          setup_completed_at: string | null
          status: string
          updated_at: string | null
        }
        Insert: {
          code: string
          contact_email?: string | null
          created_at?: string | null
          id?: string
          name: string
          settings?: Json
          setup_completed_at?: string | null
          status?: string
          updated_at?: string | null
        }
        Update: {
          code?: string
          contact_email?: string | null
          created_at?: string | null
          id?: string
          name?: string
          settings?: Json
          setup_completed_at?: string | null
          status?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      period_criteria: {
        Row: {
          color: string | null
          description: string | null
          id: string
          key: string
          label: string
          max_score: number
          period_id: string
          rubric_bands: Json | null
          sort_order: number | null
          source_criterion_id: string | null
          weight: number
        }
        Insert: {
          color?: string | null
          description?: string | null
          id?: string
          key: string
          label: string
          max_score: number
          period_id: string
          rubric_bands?: Json | null
          sort_order?: number | null
          source_criterion_id?: string | null
          weight: number
        }
        Update: {
          color?: string | null
          description?: string | null
          id?: string
          key?: string
          label?: string
          max_score?: number
          period_id?: string
          rubric_bands?: Json | null
          sort_order?: number | null
          source_criterion_id?: string | null
          weight?: number
        }
        Relationships: [
          {
            foreignKeyName: "period_criteria_period_id_fkey"
            columns: ["period_id"]
            isOneToOne: false
            referencedRelation: "periods"
            referencedColumns: ["id"]
          },
        ]
      }
      period_criterion_outcome_maps: {
        Row: {
          coverage_type: string | null
          id: string
          period_criterion_id: string
          period_id: string
          period_outcome_id: string
          weight: number | null
        }
        Insert: {
          coverage_type?: string | null
          id?: string
          period_criterion_id: string
          period_id: string
          period_outcome_id: string
          weight?: number | null
        }
        Update: {
          coverage_type?: string | null
          id?: string
          period_criterion_id?: string
          period_id?: string
          period_outcome_id?: string
          weight?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "period_criterion_outcome_maps_period_criterion_id_fkey"
            columns: ["period_criterion_id"]
            isOneToOne: false
            referencedRelation: "period_criteria"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "period_criterion_outcome_maps_period_id_fkey"
            columns: ["period_id"]
            isOneToOne: false
            referencedRelation: "periods"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "period_criterion_outcome_maps_period_outcome_id_fkey"
            columns: ["period_outcome_id"]
            isOneToOne: false
            referencedRelation: "period_outcomes"
            referencedColumns: ["id"]
          },
        ]
      }
      period_outcomes: {
        Row: {
          code: string
          coverage_type: string | null
          description: string | null
          id: string
          label: string
          period_id: string
          sort_order: number | null
          source_outcome_id: string | null
        }
        Insert: {
          code: string
          coverage_type?: string | null
          description?: string | null
          id?: string
          label: string
          period_id: string
          sort_order?: number | null
          source_outcome_id?: string | null
        }
        Update: {
          code?: string
          coverage_type?: string | null
          description?: string | null
          id?: string
          label?: string
          period_id?: string
          sort_order?: number | null
          source_outcome_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "period_outcomes_period_id_fkey"
            columns: ["period_id"]
            isOneToOne: false
            referencedRelation: "periods"
            referencedColumns: ["id"]
          },
        ]
      }
      periods: {
        Row: {
          activated_at: string | null
          closed_at: string | null
          created_at: string | null
          criteria_name: string | null
          description: string | null
          end_date: string | null
          framework_id: string | null
          id: string
          is_locked: boolean | null
          name: string
          organization_id: string
          season: string | null
          snapshot_frozen_at: string | null
          start_date: string | null
          updated_at: string | null
        }
        Insert: {
          activated_at?: string | null
          closed_at?: string | null
          created_at?: string | null
          criteria_name?: string | null
          description?: string | null
          end_date?: string | null
          framework_id?: string | null
          id?: string
          is_locked?: boolean | null
          name: string
          organization_id: string
          season?: string | null
          snapshot_frozen_at?: string | null
          start_date?: string | null
          updated_at?: string | null
        }
        Update: {
          activated_at?: string | null
          closed_at?: string | null
          created_at?: string | null
          criteria_name?: string | null
          description?: string | null
          end_date?: string | null
          framework_id?: string | null
          id?: string
          is_locked?: boolean | null
          name?: string
          organization_id?: string
          season?: string | null
          snapshot_frozen_at?: string | null
          start_date?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "periods_framework_id_fkey"
            columns: ["framework_id"]
            isOneToOne: false
            referencedRelation: "frameworks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "periods_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      platform_backups: {
        Row: {
          created_at: string
          created_by: string | null
          download_count: number
          expires_at: string | null
          format: string
          id: string
          last_downloaded_at: string | null
          organization_id: string
          origin: string
          period_ids: string[]
          row_counts: Json
          size_bytes: number
          storage_path: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          download_count?: number
          expires_at?: string | null
          format?: string
          id?: string
          last_downloaded_at?: string | null
          organization_id: string
          origin: string
          period_ids?: string[]
          row_counts?: Json
          size_bytes?: number
          storage_path: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          download_count?: number
          expires_at?: string | null
          format?: string
          id?: string
          last_downloaded_at?: string | null
          organization_id?: string
          origin?: string
          period_ids?: string[]
          row_counts?: Json
          size_bytes?: number
          storage_path?: string
        }
        Relationships: [
          {
            foreignKeyName: "platform_backups_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      platform_settings: {
        Row: {
          auto_approve_new_orgs: boolean
          backup_cron_expr: string
          id: number
          platform_name: string
          support_email: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          auto_approve_new_orgs?: boolean
          backup_cron_expr?: string
          id?: number
          platform_name?: string
          support_email?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          auto_approve_new_orgs?: boolean
          backup_cron_expr?: string
          id?: number
          platform_name?: string
          support_email?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string | null
          display_name: string | null
          email_verified_at: string | null
          id: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string | null
          display_name?: string | null
          email_verified_at?: string | null
          id: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string | null
          display_name?: string | null
          email_verified_at?: string | null
          id?: string
        }
        Relationships: []
      }
      projects: {
        Row: {
          advisor_affiliation: string | null
          advisor_name: string | null
          created_at: string | null
          description: string | null
          id: string
          members: Json
          period_id: string
          project_no: number | null
          title: string
          updated_at: string | null
        }
        Insert: {
          advisor_affiliation?: string | null
          advisor_name?: string | null
          created_at?: string | null
          description?: string | null
          id?: string
          members?: Json
          period_id: string
          project_no?: number | null
          title: string
          updated_at?: string | null
        }
        Update: {
          advisor_affiliation?: string | null
          advisor_name?: string | null
          created_at?: string | null
          description?: string | null
          id?: string
          members?: Json
          period_id?: string
          project_no?: number | null
          title?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "projects_period_id_fkey"
            columns: ["period_id"]
            isOneToOne: false
            referencedRelation: "periods"
            referencedColumns: ["id"]
          },
        ]
      }
      received_emails: {
        Row: {
          from_address: string | null
          html_body: string | null
          id: string
          raw_payload: Json | null
          received_at: string
          subject: string | null
          text_body: string | null
          to_address: string | null
        }
        Insert: {
          from_address?: string | null
          html_body?: string | null
          id?: string
          raw_payload?: Json | null
          received_at?: string
          subject?: string | null
          text_body?: string | null
          to_address?: string | null
        }
        Update: {
          from_address?: string | null
          html_body?: string | null
          id?: string
          raw_payload?: Json | null
          received_at?: string
          subject?: string | null
          text_body?: string | null
          to_address?: string | null
        }
        Relationships: []
      }
      score_sheet_items: {
        Row: {
          created_at: string | null
          id: string
          period_criterion_id: string
          score_sheet_id: string
          score_value: number | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          period_criterion_id: string
          score_sheet_id: string
          score_value?: number | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          period_criterion_id?: string
          score_sheet_id?: string
          score_value?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "score_sheet_items_period_criterion_id_fkey"
            columns: ["period_criterion_id"]
            isOneToOne: false
            referencedRelation: "period_criteria"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "score_sheet_items_score_sheet_id_fkey"
            columns: ["score_sheet_id"]
            isOneToOne: false
            referencedRelation: "score_sheets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "score_sheet_items_score_sheet_id_fkey"
            columns: ["score_sheet_id"]
            isOneToOne: false
            referencedRelation: "scores_compat"
            referencedColumns: ["id"]
          },
        ]
      }
      score_sheets: {
        Row: {
          comment: string | null
          created_at: string | null
          id: string
          juror_id: string
          last_activity_at: string | null
          period_id: string
          project_id: string
          started_at: string | null
          status: string
          updated_at: string | null
        }
        Insert: {
          comment?: string | null
          created_at?: string | null
          id?: string
          juror_id: string
          last_activity_at?: string | null
          period_id: string
          project_id: string
          started_at?: string | null
          status?: string
          updated_at?: string | null
        }
        Update: {
          comment?: string | null
          created_at?: string | null
          id?: string
          juror_id?: string
          last_activity_at?: string | null
          period_id?: string
          project_id?: string
          started_at?: string | null
          status?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "score_sheets_juror_id_fkey"
            columns: ["juror_id"]
            isOneToOne: false
            referencedRelation: "jurors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "score_sheets_period_id_fkey"
            columns: ["period_id"]
            isOneToOne: false
            referencedRelation: "periods"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "score_sheets_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
      security_policy: {
        Row: {
          id: number
          policy: Json
          updated_at: string | null
          updated_by: string | null
        }
        Insert: {
          id?: number
          policy?: Json
          updated_at?: string | null
          updated_by?: string | null
        }
        Update: {
          id?: number
          policy?: Json
          updated_at?: string | null
          updated_by?: string | null
        }
        Relationships: []
      }
      unlock_requests: {
        Row: {
          created_at: string
          id: string
          organization_id: string
          period_id: string
          reason: string
          requested_by: string
          review_note: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          status: string
        }
        Insert: {
          created_at?: string
          id?: string
          organization_id: string
          period_id: string
          reason: string
          requested_by: string
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
        }
        Update: {
          created_at?: string
          id?: string
          organization_id?: string
          period_id?: string
          reason?: string
          requested_by?: string
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "unlock_requests_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "unlock_requests_period_id_fkey"
            columns: ["period_id"]
            isOneToOne: false
            referencedRelation: "periods"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "unlock_requests_requested_by_fkey"
            columns: ["requested_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "unlock_requests_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      scores_compat: {
        Row: {
          comments: string | null
          created_at: string | null
          id: string | null
          juror_id: string | null
          oral: number | null
          period_id: string | null
          project_id: string | null
          teamwork: number | null
          technical: number | null
          updated_at: string | null
          written: number | null
        }
        Relationships: [
          {
            foreignKeyName: "score_sheets_juror_id_fkey"
            columns: ["juror_id"]
            isOneToOne: false
            referencedRelation: "jurors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "score_sheets_period_id_fkey"
            columns: ["period_id"]
            isOneToOne: false
            referencedRelation: "periods"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "score_sheets_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      _assert_can_invite: { Args: { p_org_id: string }; Returns: undefined }
      _assert_org_admin: { Args: { p_org_id: string }; Returns: undefined }
      _assert_period_unlocked: {
        Args: { p_period_id: string }
        Returns: undefined
      }
      _assert_super_admin: { Args: never; Returns: undefined }
      _assert_tenant_admin: { Args: { p_action?: string }; Returns: undefined }
      _assert_tenant_owner: { Args: { p_org_id: string }; Returns: undefined }
      _audit_verify_chain_internal: {
        Args: { p_org_id?: string }
        Returns: Json
      }
      _audit_write: {
        Args: {
          p_action: string
          p_actor_type?: Database["public"]["Enums"]["audit_actor_type"]
          p_category: Database["public"]["Enums"]["audit_category"]
          p_correlation_id?: string
          p_details: Json
          p_diff?: Json
          p_org_id: string
          p_resource_id: string
          p_resource_type: string
          p_severity: Database["public"]["Enums"]["audit_severity"]
        }
        Returns: undefined
      }
      _cleanup_unverified_expired_accounts: { Args: never; Returns: number }
      current_user_admin_org_ids: { Args: never; Returns: string[] }
      current_user_is_super_admin: { Args: never; Returns: boolean }
      email_is_verified: { Args: { uid: string }; Returns: boolean }
      rpc_accept_invite: { Args: never; Returns: undefined }
      rpc_admin_approve_application: {
        Args: { p_application_id: string }
        Returns: Json
      }
      rpc_admin_approve_join_request: {
        Args: { p_membership_id: string }
        Returns: Json
      }
      rpc_admin_cancel_maintenance: { Args: never; Returns: Json }
      rpc_admin_check_period_readiness: {
        Args: { p_period_id: string }
        Returns: Json
      }
      rpc_admin_clone_framework: {
        Args: { p_framework_id: string; p_new_name: string; p_org_id: string }
        Returns: string
      }
      rpc_admin_close_period: { Args: { p_period_id: string }; Returns: Json }
      rpc_admin_create_framework_outcome: {
        Args: {
          p_code: string
          p_description?: string
          p_framework_id: string
          p_label: string
          p_sort_order?: number
        }
        Returns: Json
      }
      rpc_admin_create_org_and_membership: {
        Args: { p_name: string; p_org_name: string }
        Returns: Json
      }
      rpc_admin_create_period_outcome: {
        Args: {
          p_code: string
          p_description?: string
          p_label: string
          p_period_id: string
          p_sort_order?: number
        }
        Returns: Json
      }
      rpc_admin_delete_framework_outcome: {
        Args: { p_outcome_id: string }
        Returns: Json
      }
      rpc_admin_delete_organization: {
        Args: { p_org_id: string }
        Returns: undefined
      }
      rpc_admin_delete_period_criterion_outcome_map: {
        Args: { p_map_id: string }
        Returns: Json
      }
      rpc_admin_delete_period_outcome: {
        Args: { p_outcome_id: string }
        Returns: Json
      }
      rpc_admin_duplicate_period: {
        Args: { p_source_period_id: string }
        Returns: string
      }
      rpc_admin_find_user_by_email: {
        Args: { p_email: string }
        Returns: {
          email_confirmed_at: string
          id: string
        }[]
      }
      rpc_admin_force_close_juror_edit_mode: {
        Args: { p_juror_id: string; p_period_id: string }
        Returns: Json
      }
      rpc_admin_generate_entry_token: {
        Args: { p_period_id: string }
        Returns: string
      }
      rpc_admin_get_backup_schedule: { Args: never; Returns: Json }
      rpc_admin_get_maintenance: { Args: never; Returns: Json }
      rpc_admin_get_pin_policy: { Args: never; Returns: Json }
      rpc_admin_get_platform_settings: { Args: never; Returns: Json }
      rpc_admin_get_security_policy: { Args: never; Returns: Json }
      rpc_admin_hard_delete_org_member: {
        Args: { p_org_id: string; p_user_id: string }
        Returns: Json
      }
      rpc_admin_list_organizations: { Args: never; Returns: Json }
      rpc_admin_list_unlock_requests: {
        Args: { p_status?: string }
        Returns: Json
      }
      rpc_admin_log_period_lock: {
        Args: { p_action: string; p_ctx: Json; p_period_id: string }
        Returns: Json
      }
      rpc_admin_mark_setup_complete: {
        Args: { p_org_id: string }
        Returns: string
      }
      rpc_admin_period_unassign_framework: {
        Args: { p_period_id: string }
        Returns: Json
      }
      rpc_admin_publish_period: { Args: { p_period_id: string }; Returns: Json }
      rpc_admin_reject_application: {
        Args: { p_application_id: string }
        Returns: Json
      }
      rpc_admin_reject_join_request: {
        Args: { p_membership_id: string }
        Returns: Json
      }
      rpc_admin_reorder_period_criteria: {
        Args: { p_keys: Json; p_period_id: string }
        Returns: undefined
      }
      rpc_admin_request_unlock: {
        Args: { p_period_id: string; p_reason: string }
        Returns: Json
      }
      rpc_admin_revoke_admin_session: {
        Args: { p_session_id: string }
        Returns: Json
      }
      rpc_admin_revoke_entry_token: {
        Args: { p_period_id: string }
        Returns: Json
      }
      rpc_admin_save_period_criteria: {
        Args: { p_criteria: Json; p_period_id: string }
        Returns: Json
      }
      rpc_admin_set_backup_schedule: {
        Args: { p_cron_expr: string }
        Returns: Json
      }
      rpc_admin_set_maintenance: {
        Args: {
          p_affected_org_ids?: string[]
          p_duration_min?: number
          p_message?: string
          p_mode: string
          p_notify_admins?: boolean
          p_start_time?: string
        }
        Returns: Json
      }
      rpc_admin_set_period_criteria_name: {
        Args: { p_name: string; p_period_id: string }
        Returns: undefined
      }
      rpc_admin_set_period_lock: {
        Args: { p_locked: boolean; p_period_id: string }
        Returns: Json
      }
      rpc_admin_set_pin_policy: {
        Args: { p_cooldown: string; p_max_attempts: number; p_qr_ttl: string }
        Returns: Json
      }
      rpc_admin_set_platform_settings: {
        Args: {
          p_auto_approve_new_orgs: boolean
          p_platform_name: string
          p_support_email: string
        }
        Returns: Json
      }
      rpc_admin_set_security_policy: { Args: { p_policy: Json }; Returns: Json }
      rpc_admin_super_create_organization: {
        Args: {
          p_code: string
          p_contact_email?: string
          p_name: string
          p_status?: string
        }
        Returns: Json
      }
      rpc_admin_update_framework_outcome: {
        Args: { p_outcome_id: string; p_patch: Json }
        Returns: Json
      }
      rpc_admin_update_member_profile: {
        Args: {
          p_display_name: string
          p_organization_id: string
          p_user_id: string
        }
        Returns: Json
      }
      rpc_admin_update_organization: {
        Args: { p_org_id: string; p_updates: Json }
        Returns: Json
      }
      rpc_admin_update_period_outcome: {
        Args: { p_outcome_id: string; p_patch: Json }
        Returns: Json
      }
      rpc_admin_upsert_period_criterion_outcome_map: {
        Args: {
          p_coverage_type?: string
          p_period_criterion_id: string
          p_period_id: string
          p_period_outcome_id: string
        }
        Returns: Json
      }
      rpc_admin_verify_audit_chain: {
        Args: { p_org_id: string }
        Returns: Json
      }
      rpc_admin_write_audit_event: { Args: { p_event: Json }; Returns: Json }
      rpc_admin_write_audit_log: {
        Args: {
          p_action: string
          p_details?: Json
          p_organization_id?: string
          p_resource_id?: string
          p_resource_type?: string
        }
        Returns: undefined
      }
      rpc_backup_delete: {
        Args: { p_backup_id: string }
        Returns: {
          storage_path: string
        }[]
      }
      rpc_backup_list: {
        Args: { p_organization_id: string }
        Returns: {
          created_at: string
          created_by: string
          created_by_name: string
          download_count: number
          expires_at: string
          format: string
          id: string
          last_downloaded_at: string
          organization_id: string
          origin: string
          period_ids: string[]
          row_counts: Json
          size_bytes: number
          storage_path: string
        }[]
      }
      rpc_backup_record_download: {
        Args: { p_backup_id: string }
        Returns: undefined
      }
      rpc_backup_register: {
        Args: {
          p_format: string
          p_organization_id: string
          p_origin?: string
          p_period_ids: string[]
          p_row_counts: Json
          p_size_bytes: number
          p_storage_path: string
        }
        Returns: string
      }
      rpc_check_email_available: { Args: { p_email: string }; Returns: Json }
      rpc_entry_token_revoke: { Args: { p_token_id: string }; Returns: Json }
      rpc_get_period_impact: {
        Args: { p_period_id: string; p_session_token: string }
        Returns: Json
      }
      rpc_get_public_feedback: { Args: never; Returns: Json }
      rpc_juror_reset_pin: {
        Args: { p_juror_id: string; p_period_id: string }
        Returns: Json
      }
      rpc_juror_toggle_edit_mode: {
        Args: {
          p_duration_minutes?: number
          p_enabled: boolean
          p_juror_id: string
          p_period_id: string
          p_reason?: string
        }
        Returns: Json
      }
      rpc_juror_unlock_pin: {
        Args: { p_juror_id: string; p_period_id: string }
        Returns: Json
      }
      rpc_jury_authenticate: {
        Args: {
          p_affiliation: string
          p_email?: string
          p_force_reissue?: boolean
          p_juror_name: string
          p_period_id: string
        }
        Returns: Json
      }
      rpc_jury_finalize_submission: {
        Args: {
          p_correlation_id?: string
          p_juror_id: string
          p_period_id: string
          p_session_token: string
        }
        Returns: Json
      }
      rpc_jury_get_edit_state: {
        Args: { p_juror_id: string; p_period_id: string }
        Returns: Json
      }
      rpc_jury_get_scores: {
        Args: {
          p_juror_id: string
          p_period_id: string
          p_session_token: string
        }
        Returns: Json
      }
      rpc_jury_project_rankings: {
        Args: { p_period_id: string; p_session_token: string }
        Returns: {
          avg_score: number
          project_id: string
        }[]
      }
      rpc_jury_upsert_score: {
        Args: {
          p_comment?: string
          p_juror_id: string
          p_period_id: string
          p_project_id: string
          p_scores: Json
          p_session_token: string
        }
        Returns: Json
      }
      rpc_jury_validate_entry_reference: {
        Args: { p_reference: string }
        Returns: Json
      }
      rpc_jury_validate_entry_token: {
        Args: { p_token: string }
        Returns: Json
      }
      rpc_jury_verify_pin: {
        Args: {
          p_affiliation: string
          p_juror_name: string
          p_period_id: string
          p_pin: string
        }
        Returns: Json
      }
      rpc_landing_stats: { Args: never; Returns: Json }
      rpc_org_admin_cancel_invite: {
        Args: { p_membership_id: string }
        Returns: Json
      }
      rpc_org_admin_list_members: { Args: never; Returns: Json }
      rpc_org_admin_remove_member: {
        Args: { p_membership_id: string }
        Returns: Json
      }
      rpc_org_admin_set_admins_can_invite: {
        Args: { p_enabled: boolean; p_org_id: string }
        Returns: Json
      }
      rpc_org_admin_transfer_ownership: {
        Args: { p_target_membership_id: string }
        Returns: Json
      }
      rpc_period_freeze_snapshot: {
        Args: { p_force?: boolean; p_period_id: string }
        Returns: Json
      }
      rpc_platform_metrics: { Args: never; Returns: Json }
      rpc_public_auth_flags: { Args: never; Returns: Json }
      rpc_public_maintenance_status: { Args: never; Returns: Json }
      rpc_public_platform_settings: { Args: never; Returns: Json }
      rpc_public_search_organizations: {
        Args: { p_query: string }
        Returns: Json
      }
      rpc_request_to_join_org: { Args: { p_org_id: string }; Returns: Json }
      rpc_submit_jury_feedback: {
        Args: {
          p_comment?: string
          p_period_id: string
          p_rating: number
          p_session_token: string
        }
        Returns: Json
      }
      rpc_super_admin_resolve_unlock: {
        Args: { p_decision: string; p_note?: string; p_request_id: string }
        Returns: Json
      }
      rpc_write_auth_failure_event: {
        Args: { p_email: string; p_method?: string }
        Returns: Json
      }
    }
    Enums: {
      audit_actor_type: "admin" | "juror" | "system" | "anonymous"
      audit_category: "auth" | "access" | "data" | "config" | "security"
      audit_severity: "info" | "low" | "medium" | "high" | "critical"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      audit_actor_type: ["admin", "juror", "system", "anonymous"],
      audit_category: ["auth", "access", "data", "config", "security"],
      audit_severity: ["info", "low", "medium", "high", "critical"],
    },
  },
} as const
