import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import crypto from 'crypto';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// deterministic utility
let _seed = 0.20260402;
function random() {
  const x = Math.sin(_seed++) * 10000;
  return x - Math.floor(x);
}

function randInt(min, max) {
  return Math.floor(random() * (max - min + 1)) + min;
}

function pick(arr) {
  return arr[Math.floor(random() * arr.length)];
}

function uuid(seedStr) {
  const hash = crypto.createHash('md5').update(seedStr).digest('hex');
  return `${hash.slice(0, 8)}-${hash.slice(8, 12)}-4${hash.slice(13, 16)}-a${hash.slice(17, 20)}-${hash.slice(20, 32)}`;
}

function sha256(val) {
  return crypto.createHash('sha256').update(val).digest('hex');
}

function escapeSql(str) {
  if (!str) return '';
  return str.replace(/'/g, "''");
}


const BASE_TIME = `timestamp '2026-05-10 12:00:00'`;

let out = [];

out.push(`-- VERA Demo Seed`);
out.push(`-- Generated by scripts/generate_demo_seed.js`);
out.push(`-- 6 orgs, 36 jurors, 71 projects, realistic scores & audit logs`);
out.push(`SELECT setseed(0.20260402);`);
out.push(`BEGIN;\n`);

out.push(`-- Pre-seed Cleanup`);
out.push(`TRUNCATE TABLE
  jury_feedback,
  audit_logs,
  entry_tokens,
  score_sheet_items,
  score_sheets,
  juror_period_auth,
  jurors,
  projects,
  period_criterion_outcome_maps,
  period_criteria,
  period_outcomes,
  periods,
  framework_criterion_outcome_maps,
  framework_criteria,
  framework_outcomes,
  frameworks,
  memberships,
  org_applications,
  organizations,
  profiles
CASCADE;
`);

// ORGS
const orgs = [
  { p: 1, name: 'Electrical-Electronics Engineering', institution: 'TED University', code: 'TEDU-EE', type: 'University department' },
  { p: 2, name: 'Computer Science', institution: 'Carnegie Mellon University', code: 'CMU-CS', type: 'University department' },
  { p: 3, name: 'TEKNOFEST', institution: 'Türkiye Technology Team Foundation', code: 'TEKNOFEST', type: 'Technology competition' },
  { p: 4, name: 'TÜBİTAK 2204-A', institution: 'Scientific and Technological Research Council of Türkiye', code: 'TUBITAK-2204A', type: 'Research competition' },
  { p: 5, name: 'AP-S Student Design Contest', institution: 'IEEE Antennas and Propagation Society', code: 'IEEE-APSSDC', type: 'Design contest' },
  { p: 6, name: 'CanSat Competition', institution: 'American Astronautical Society', code: 'CANSAT-2025', type: 'Competition' }
];

out.push(`-- Organizations`);
orgs.forEach(o => {
  o.id = uuid('org-' + o.code);
  out.push(`INSERT INTO organizations (id, subtitle, name, code, status, settings, updated_at) VALUES ('${o.id}', '${escapeSql(o.institution)}', '${escapeSql(o.name)}', '${o.code}', 'active', '{}', ${BASE_TIME}) ON CONFLICT DO NOTHING;`);
});
out.push('');

// PROFILES
const demoAdminId = '6ea7146f-1331-4828-8b8a-e777c9a35d6a';
out.push(`-- Identities`);
out.push(`INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token) VALUES ('00000000-0000-0000-0000-000000000000', '${demoAdminId}', 'authenticated', 'authenticated', 'admin@vera.app', '', now(), now(), now(), '', '', '', '') ON CONFLICT DO NOTHING;`);
out.push(`INSERT INTO profiles (id, display_name) VALUES ('${demoAdminId}', 'Vera Platform Admin') ON CONFLICT DO NOTHING;`);
out.push(`INSERT INTO memberships (user_id, organization_id, role) VALUES ('${demoAdminId}', NULL, 'super_admin') ON CONFLICT DO NOTHING;`);

let orgAdminIds = [];
// Deterministic admin names per org — no duplicates, no org-code suffixes
const orgAdminNames = {
  'TEDU-EE':      ['Prof. Koray Yılmazer', 'Dr. Leyla Şensoy'],
  'CMU-CS':       ['Prof. Marcus Reynolds', 'Dr. Chloe Beckett'],
  'TEKNOFEST':    ['Cemil Bozkurt', 'Bahar Tandoğan'],
  'TUBITAK-2204A':['Prof. Ayşe Karataş'],
  'IEEE-APSSDC':  ['Dr. Gavin Pierce'],
  'CANSAT-2025':  ['Harper Quinn']
};

orgs.forEach(o => {
  const names = orgAdminNames[o.code] || [];
  names.forEach((nm, i) => {
    const idx = i + 1;
    let pId = uuid('prof-admin-' + o.code + '-' + idx);
    const emailName = nm.replace(/^(Prof\.|Dr\.|Col\.)\s*/i, '').toLowerCase().replace(/\s+/g, '.').replace(/[şŞ]/g, 's').replace(/[çÇ]/g, 'c').replace(/[ğĞ]/g, 'g').replace(/[ıİ]/g, 'i').replace(/[öÖ]/g, 'o').replace(/[üÜ]/g, 'u');
    let fakeEmail = `${emailName}@vera-eval.app`;
    out.push(`INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token) VALUES ('00000000-0000-0000-0000-000000000000', '${pId}', 'authenticated', 'authenticated', '${fakeEmail}', '', now(), now(), now(), '', '', '', '') ON CONFLICT DO NOTHING;`);
    out.push(`INSERT INTO profiles (id, display_name) VALUES ('${pId}', '${escapeSql(nm)}') ON CONFLICT DO NOTHING;`);
    out.push(`INSERT INTO memberships (user_id, organization_id, role) VALUES ('${pId}', '${o.id}', 'org_admin') ON CONFLICT DO NOTHING;`);
    orgAdminIds.push(pId);
  });
});
out.push('');

// APP/MEMBERSHIPS 
const applicantNames = ['Prof. Halil Çankaya', 'Dr. Rachel Voss', 'Oğuzhan Demirel', 'Dr. Ayça Gürkan', 'Prof. Arthur Finch', 'Celine Moreau'];
const appStatuses = ['approved', 'approved', 'rejected', 'cancelled', 'pending', 'pending'];
const orgAppIds = [];

orgs.forEach((o, i) => {
  let appUuid = uuid('app-' + o.code);
  let applicant = applicantNames[i];
  out.push(`INSERT INTO org_applications (id, organization_id, applicant_name, contact_email, status) VALUES ('${appUuid}', '${o.id}', '${escapeSql(applicant)}', '${o.code.toLowerCase()}@example.edu', '${appStatuses[i]}') ON CONFLICT DO NOTHING;`);
  orgAppIds.push({id: appUuid, org: o.code});
});
out.push('');

// FRAMEWORKS
const fws = [];
const fwOutcomes = [];
const fwCriteria = [];
const fwMaps = [];

function parseRubric(maxScore) {
  let rubric = [];
  if (maxScore >= 25) {
    let b1 = Math.floor(maxScore * 0.88);
    let b2 = Math.floor(maxScore * 0.68);
    let b3 = Math.floor(maxScore * 0.48);
    rubric.push({min: b1, max: maxScore, label: 'Excellent', description: 'Outstanding performance'});
    rubric.push({min: b2, max: b1-1, label: 'Good', description: 'Above average, minor gaps'});
    rubric.push({min: b3, max: b2-1, label: 'Developing', description: 'Meets minimum, needs improvement'});
    rubric.push({min: 0, max: b3-1, label: 'Insufficient', description: 'Below acceptable standard'});
  } else if (maxScore >= 20) {
    rubric = [
      {min: 18, max: 20, label: 'Excellent', description: 'Outstanding performance'},
      {min: 14, max: 17, label: 'Good', description: 'Above average, minor gaps'},
      {min: 10, max: 13, label: 'Developing', description: 'Meets minimum'},
      {min: 0, max: 9, label: 'Insufficient', description: 'Below standard'}
    ];
  } else {
    rubric = [
      {min: 9, max: 10, label: 'Excellent', description: 'Outstanding'},
      {min: 7, max: 8, label: 'Good', description: 'Above average'},
      {min: 5, max: 6, label: 'Developing', description: 'Meets minimum'},
      {min: 0, max: 4, label: 'Insufficient', description: 'Below standard'}
    ];
  }
  return JSON.stringify(rubric).replace(/'/g, "''");
}

function processOrgfw(orgCode, fwName, fwVersion, criteria, outcomes, mappings) {
  const o = orgs.find(x => x.code === orgCode);
  const fwId = uuid('fw-' + orgCode);
  fws.push(`INSERT INTO frameworks (id, organization_id, name, version, is_default) VALUES ('${fwId}', '${o.id}', '${escapeSql(fwName)}', '${fwVersion}', true) ON CONFLICT DO NOTHING;`);
  
  const oMap = {};
  let outOrder = 1;
  o.outcomesData = [];
  for (const arr of outcomes) {
    const [code, lbl] = arr;
    const oId = uuid(`fw-out-${orgCode}-${code}`);
    oMap[code] = oId;
    o.outcomesData.push({ id: oId, code, label: lbl, sortOrder: outOrder });
    fwOutcomes.push(`INSERT INTO framework_outcomes (id, framework_id, code, label, sort_order) VALUES ('${oId}', '${fwId}', '${escapeSql(code)}', '${escapeSql(lbl)}', ${outOrder++}) ON CONFLICT DO NOTHING;`);
  }

  const cMap = {};
  let critOrder = 1;
  o.criteriaData = [];
  for (const c of criteria) {
    const cId = uuid(`fw-crit-${orgCode}-${c.key}`);
    const rubricJson = c.customRubric ? JSON.stringify(c.customRubric).replace(/'/g, "''") : parseRubric(c.max);
    cMap[c.key] = cId;
    o.criteriaData.push({ id: cId, ...c, sortOrder: critOrder });
    fwCriteria.push(`INSERT INTO framework_criteria (id, framework_id, key, label, short_label, max_score, weight, color, rubric_bands, sort_order) VALUES ('${cId}', '${fwId}', '${c.key}', '${escapeSql(c.label)}', '${escapeSql(c.short)}', ${c.max}, ${c.weight}, '${c.color}', '${rubricJson}', ${critOrder++}) ON CONFLICT DO NOTHING;`);
  }

  o.mapsData = [];
  for (const m of mappings) {
    const cId = cMap[m.crit];
    for (const mo of m.outs) {
      const oId = oMap[mo.code];
      const mId = uuid(`fw-map-${orgCode}-${m.crit}-${mo.code}`);
      o.mapsData.push({ id: mId, cId, oId, weight: mo.weight });
      fwMaps.push(`INSERT INTO framework_criterion_outcome_maps (id, framework_id, criterion_id, outcome_id, weight) VALUES ('${mId}', '${fwId}', '${cId}', '${oId}', ${mo.weight}) ON CONFLICT DO NOTHING;`);
    }
  }
}

// Setup matching frameworks...
processOrgfw('TEDU-EE', 'MUDEK 2024', '1.0', 
  [
    {
      key:'technical', label:'Technical Content', short:'Technical', max:30, weight:30, color:'#F59E0B',
      customRubric: [
        { min: 27, max: 30, label: 'Excellent', description: 'Problem is clearly defined with strong motivation. Design decisions are well-justified with engineering depth. Originality and mastery of relevant tools or methods are evident.' },
        { min: 21, max: 26, label: 'Good', description: 'Design is mostly clear and technically justified. Engineering decisions are largely supported.' },
        { min: 13, max: 20, label: 'Developing', description: 'Problem is stated but motivation or technical justification is insufficient.' },
        { min: 0, max: 12, label: 'Insufficient', description: 'Vague problem definition and unjustified decisions. Superficial technical content.' },
      ]
    },
    {
      key:'design', label:'Written Communication', short:'Written', max:30, weight:30, color:'#22C55E',
      customRubric: [
        { min: 27, max: 30, label: 'Excellent', description: 'Poster layout is intuitive with clear information flow. Visuals are fully labelled and high quality. Technical content is presented in a way that is accessible to both technical and non-technical readers.' },
        { min: 21, max: 26, label: 'Good', description: 'Layout is mostly logical. Visuals are readable with minor gaps. Technical content is largely clear with small areas for improvement.' },
        { min: 13, max: 20, label: 'Developing', description: 'Occasional gaps in information flow. Some visuals are missing labels or captions. Technical content is only partially communicated.' },
        { min: 0, max: 12, label: 'Insufficient', description: 'Confusing layout. Low-quality or unlabelled visuals. Technical content is unclear or missing.' },
      ]
    },
    {
      key:'delivery', label:'Oral Communication', short:'Oral', max:30, weight:30, color:'#3B82F6',
      customRubric: [
        { min: 27, max: 30, label: 'Excellent', description: 'Presentation is consciously adapted for both technical and non-technical jury members. Q&A responses are accurate, clear, and audience-appropriate.' },
        { min: 21, max: 26, label: 'Good', description: 'Presentation is mostly clear and well-paced. Most questions answered correctly. Audience adaptation is generally evident.' },
        { min: 13, max: 20, label: 'Developing', description: 'Understandable but inconsistent. Limited audience adaptation. Time management or Q&A depth needs improvement.' },
        { min: 0, max: 12, label: 'Insufficient', description: 'Unclear or disorganised presentation. Most questions answered incorrectly or not at all.' },
      ]
    },
    {
      key:'teamwork', label:'Teamwork', short:'Teamwork', max:10, weight:10, color:'#EF4444',
      customRubric: [
        { min: 9, max: 10, label: 'Excellent', description: 'All members participate actively and equally. Professional and ethical conduct observed throughout.' },
        { min: 7, max: 8, label: 'Good', description: 'Most members contribute. Minor knowledge gaps. Professionalism mostly observed.' },
        { min: 4, max: 6, label: 'Developing', description: 'Uneven participation. Some members are passive or unprepared.' },
        { min: 0, max: 3, label: 'Insufficient', description: 'Very low participation or dominated by one person. Lack of professionalism observed.' },
      ]
    }
  ],
  [
    ['1.2', 'Adequate knowledge in mathematics, science and engineering'], ['2', 'Ability to formulate and solve complex engineering problems'],
    ['3.1', 'Ability to design a complex system under realistic constraints'], ['3.2', 'Ability to apply modern design methods'],
    ['8.1', 'Ability to function effectively in teams'], ['8.2', 'Ability to work in multi-disciplinary teams'],
    ['9.1', 'Oral communication effectiveness'], ['9.2', 'Written communication effectiveness']
  ],
  [
    {crit:'technical', outs:[{code:'1.2',weight:0.25}, {code:'2',weight:0.25}, {code:'3.1',weight:0.25}, {code:'3.2',weight:0.25}]},
    {crit:'design', outs:[{code:'9.2',weight:1.0}]},
    {crit:'delivery', outs:[{code:'9.1',weight:1.0}]},
    {crit:'teamwork', outs:[{code:'8.1',weight:0.5}, {code:'8.2',weight:0.5}]}
  ]
);

processOrgfw('CMU-CS', 'ABET 2024', '1.0',
  [
    {key:'problem_solving', label:'Problem Solving & Analysis', short:'Problem', max:25, weight:25, color:'#EF4444',
      customRubric: [
        { min: 22, max: 25, label: 'Excellent', description: 'Problem is precisely formulated with clear scope, constraints, and success metrics. Analysis demonstrates strong algorithmic reasoning and consideration of edge cases.' },
        { min: 17, max: 21, label: 'Good', description: 'Problem is well-defined and analysis covers main scenarios. Minor gaps in constraint handling or edge case reasoning.' },
        { min: 12, max: 16, label: 'Developing', description: 'Problem statement exists but lacks precision. Analysis addresses common cases but overlooks important constraints.' },
        { min: 0, max: 11, label: 'Insufficient', description: 'Problem is vaguely defined. Analysis is superficial with significant logical gaps.' },
      ]
    },
    {key:'system_design', label:'System Design & Architecture', short:'Design', max:25, weight:25, color:'#3B82F6',
      customRubric: [
        { min: 22, max: 25, label: 'Excellent', description: 'Architecture is modular, scalable, and well-justified. Design decisions account for performance, maintainability, and future extensibility.' },
        { min: 17, max: 21, label: 'Good', description: 'Architecture is sound with clear component boundaries. Most design trade-offs are discussed and justified.' },
        { min: 12, max: 16, label: 'Developing', description: 'Basic architecture is present but modularity or scalability concerns are not addressed. Some components are tightly coupled.' },
        { min: 0, max: 11, label: 'Insufficient', description: 'No clear architecture. Components are ad-hoc with no separation of concerns.' },
      ]
    },
    {key:'implementation_quality', label:'Implementation Quality', short:'Impl', max:20, weight:20, color:'#F59E0B',
      customRubric: [
        { min: 18, max: 20, label: 'Excellent', description: 'Code is clean, well-tested, and follows best practices. Automated tests cover critical paths. CI/CD pipeline is functional.' },
        { min: 14, max: 17, label: 'Good', description: 'Code is readable with adequate test coverage. Minor style inconsistencies or missing tests for edge cases.' },
        { min: 10, max: 13, label: 'Developing', description: 'Code works but lacks tests or consistent style. Some technical debt is visible.' },
        { min: 0, max: 9, label: 'Insufficient', description: 'Code is disorganized, untested, or non-functional in key areas.' },
      ]
    },
    {key:'communication', label:'Communication & Documentation', short:'Comm', max:20, weight:20, color:'#EC4899',
      customRubric: [
        { min: 18, max: 20, label: 'Excellent', description: 'Documentation is thorough and developer-friendly. Presentation clearly conveys technical decisions to both technical and non-technical audiences.' },
        { min: 14, max: 17, label: 'Good', description: 'Documentation covers key areas. Presentation is clear with minor gaps in audience adaptation.' },
        { min: 10, max: 13, label: 'Developing', description: 'Documentation exists but is incomplete. Presentation conveys the main idea but lacks depth or clarity.' },
        { min: 0, max: 9, label: 'Insufficient', description: 'Little to no documentation. Presentation is unclear or fails to convey the project purpose.' },
      ]
    },
    {key:'teamwork', label:'Teamwork & Collaboration', short:'Team', max:10, weight:10, color:'#10B981',
      customRubric: [
        { min: 9, max: 10, label: 'Excellent', description: 'All members contribute meaningfully. Version control history shows balanced collaboration. Peer feedback is positive.' },
        { min: 7, max: 8, label: 'Good', description: 'Most members contribute. Collaboration is evident though workload distribution has minor imbalances.' },
        { min: 4, max: 6, label: 'Developing', description: 'Uneven contributions. Some members are passive or their work is not well-integrated.' },
        { min: 0, max: 3, label: 'Insufficient', description: 'One or two members did most of the work. Little evidence of collaboration.' },
      ]
    }
  ],
  [
    ['SO-1', 'Complex Problem Solving'], ['SO-2', 'Engineering Design'], ['SO-3', 'Effective Communication'],
    ['SO-4', 'Ethics and Professional Responsibility'], ['SO-5', 'Teamwork'], ['SO-6', 'Experimentation and Analysis'],
    ['SO-7', 'Lifelong Learning']
  ],
  [
    {crit:'problem_solving', outs:[{code:'SO-1',weight:0.6}, {code:'SO-6',weight:0.4}]},
    {crit:'system_design', outs:[{code:'SO-2',weight:0.7}, {code:'SO-1',weight:0.3}]},
    {crit:'implementation_quality', outs:[{code:'SO-6',weight:0.5}, {code:'SO-2',weight:0.3}, {code:'SO-7',weight:0.2}]},
    {crit:'communication', outs:[{code:'SO-3',weight:0.7}, {code:'SO-4',weight:0.3}]},
    {crit:'teamwork', outs:[{code:'SO-5',weight:1.0}]}
  ]
);

processOrgfw('TEKNOFEST', 'Competition Framework 2026', '2026',
  [
    {key:'preliminary_report', label:'Preliminary Design Report (ODR)', short:'Report', max:25, weight:25, color:'#6366F1',
      customRubric: [
        { min: 22, max: 25, label: 'Excellent', description: 'Report is comprehensive with clear mission definition, detailed requirements analysis, and feasible preliminary design. Literature review is thorough and relevant.' },
        { min: 17, max: 21, label: 'Good', description: 'Report covers key design elements with adequate justification. Some requirements lack depth or traceability.' },
        { min: 12, max: 16, label: 'Developing', description: 'Report structure is present but design rationale is weak. Requirements are listed without analysis.' },
        { min: 0, max: 11, label: 'Insufficient', description: 'Report is incomplete or missing critical sections. No clear design direction.' },
      ]
    },
    {key:'critical_design', label:'Critical Design Review (KTR)', short:'CDR', max:30, weight:30, color:'#F59E0B',
      customRubric: [
        { min: 27, max: 30, label: 'Excellent', description: 'Design is mature, manufacturable, and all subsystems are well-integrated. Test plans are detailed with clear pass/fail criteria. Risk analysis is thorough.' },
        { min: 21, max: 26, label: 'Good', description: 'Design is mostly complete with minor integration gaps. Test plans exist but some criteria are vague.' },
        { min: 13, max: 20, label: 'Developing', description: 'Design shows progress but subsystem integration is unclear. Test planning is insufficient.' },
        { min: 0, max: 12, label: 'Insufficient', description: 'Design is immature or not viable for manufacturing. Critical subsystems are undefined.' },
      ]
    },
    {key:'technical_performance', label:'Technical Performance & Demo', short:'Performance', max:30, weight:30, color:'#EF4444',
      customRubric: [
        { min: 27, max: 30, label: 'Excellent', description: 'System performs flawlessly in field conditions. All mission objectives are met. Data telemetry is accurate and real-time. Safety protocols are followed precisely.' },
        { min: 21, max: 26, label: 'Good', description: 'System completes primary mission with minor deviations. Most telemetry data is reliable. Safety is maintained.' },
        { min: 13, max: 20, label: 'Developing', description: 'System partially completes mission. Significant telemetry gaps or performance below specifications.' },
        { min: 0, max: 12, label: 'Insufficient', description: 'System fails to complete primary mission or poses safety concerns during operation.' },
      ]
    },
    {key:'team_execution', label:'Team Execution & Presentation', short:'Team', max:15, weight:15, color:'#10B981',
      customRubric: [
        { min: 14, max: 15, label: 'Excellent', description: 'Team operates cohesively with clear role distribution. Presentation is confident, well-structured, and all members respond competently to jury questions.' },
        { min: 11, max: 13, label: 'Good', description: 'Team coordination is evident. Presentation is organized with most questions handled well.' },
        { min: 7, max: 10, label: 'Developing', description: 'Team roles are unclear. Presentation lacks structure or Q&A responses are inconsistent.' },
        { min: 0, max: 6, label: 'Insufficient', description: 'Poor team coordination. Presentation is disorganized and questions are mostly unanswered.' },
      ]
    }
  ],
  [
    ['TC-1', 'Preliminary Evaluation Report Quality'], ['TC-2', 'Critical Design Maturity'],
    ['TC-3', 'Field Performance and Jury Presentation'], ['TC-4', 'General Team Competency']
  ],
  [
    {crit:'preliminary_report', outs:[{code:'TC-1',weight:1.0}]},
    {crit:'critical_design', outs:[{code:'TC-2',weight:0.7}, {code:'TC-1',weight:0.3}]},
    {crit:'technical_performance', outs:[{code:'TC-3',weight:0.8}, {code:'TC-2',weight:0.2}]},
    {crit:'team_execution', outs:[{code:'TC-4',weight:0.6}, {code:'TC-3',weight:0.4}]}
  ]
);

processOrgfw('TUBITAK-2204A', 'Research Competition Framework', '2204A',
  [
    {key:'originality', label:'Originality & Creativity', short:'Originality', max:35, weight:35, color:'#8B5CF6',
      customRubric: [
        { min: 31, max: 35, label: 'Excellent', description: 'Research question is novel and addresses a genuine gap in the literature. Approach is creative and shows independent thinking beyond textbook methods.' },
        { min: 24, max: 30, label: 'Good', description: 'Research topic has originality with a clear contribution. Methodology shows some creative adaptation of known approaches.' },
        { min: 17, max: 23, label: 'Developing', description: 'Topic is relevant but well-trodden. Approach closely follows established methods without meaningful innovation.' },
        { min: 0, max: 16, label: 'Insufficient', description: 'No original contribution. Work is a replication or compilation of existing material without novel insight.' },
      ]
    },
    {key:'scientific_method', label:'Scientific Method & Rigor', short:'Method', max:40, weight:40, color:'#3B82F6',
      customRubric: [
        { min: 35, max: 40, label: 'Excellent', description: 'Hypothesis is clearly stated and testable. Experimental design includes proper controls, adequate sample size, and reproducible procedures. Statistical analysis is appropriate and correctly applied.' },
        { min: 27, max: 34, label: 'Good', description: 'Methodology is sound with minor gaps in controls or sample size justification. Data analysis is mostly correct.' },
        { min: 19, max: 26, label: 'Developing', description: 'Basic methodology is present but controls are weak or missing. Statistical analysis is incomplete or partially incorrect.' },
        { min: 0, max: 18, label: 'Insufficient', description: 'No clear hypothesis or experimental design. Data collection and analysis are unreliable or absent.' },
      ]
    },
    {key:'impact_and_presentation', label:'Impact & Presentation', short:'Impact', max:25, weight:25, color:'#F59E0B',
      customRubric: [
        { min: 22, max: 25, label: 'Excellent', description: 'Results have clear real-world applicability. Poster and oral presentation are professionally prepared, logically structured, and accessible to a broad scientific audience.' },
        { min: 17, max: 21, label: 'Good', description: 'Potential impact is described. Presentation is organized with good visual aids, though some sections could be clearer.' },
        { min: 12, max: 16, label: 'Developing', description: 'Impact is mentioned but not convincingly argued. Presentation has structural issues or unclear visuals.' },
        { min: 0, max: 11, label: 'Insufficient', description: 'No discussion of impact or applicability. Presentation is poorly organized or incomprehensible.' },
      ]
    }
  ],
  [
    ['RC-1', 'Originality and Creativity'], ['RC-2', 'Scientific Method'], ['RC-3', 'Results and Recommendations'],
    ['RC-4', 'Applicability and Feasibility'], ['RC-5', 'Broader Impact']
  ],
  [
    {crit:'originality', outs:[{code:'RC-1',weight:0.7}, {code:'RC-4',weight:0.3}]},
    {crit:'scientific_method', outs:[{code:'RC-2',weight:0.5}, {code:'RC-3',weight:0.5}]},
    {crit:'impact_and_presentation', outs:[{code:'RC-5',weight:0.5}, {code:'RC-3',weight:0.3}, {code:'RC-4',weight:0.2}]}
  ]
);

processOrgfw('IEEE-APSSDC', 'Design Contest Framework', '1.0',
  [
    {key:'creativity', label:'Creativity & Innovation', short:'Creativity', max:30, weight:30, color:'#EC4899',
      customRubric: [
        { min: 27, max: 30, label: 'Excellent', description: 'Antenna design demonstrates a novel topology or technique not commonly seen in the literature. Creative use of materials, fabrication methods, or multi-functional integration is evident.' },
        { min: 21, max: 26, label: 'Good', description: 'Design shows originality in at least one dimension (topology, feed network, or application). Builds meaningfully on prior work.' },
        { min: 13, max: 20, label: 'Developing', description: 'Design follows conventional approaches with minor modifications. Limited evidence of original thinking.' },
        { min: 0, max: 12, label: 'Insufficient', description: 'Design is a direct copy of a textbook or published antenna with no meaningful contribution.' },
      ]
    },
    {key:'technical_merit', label:'Technical Merit', short:'Technical', max:40, weight:40, color:'#3B82F6',
      customRubric: [
        { min: 35, max: 40, label: 'Excellent', description: 'Simulation and measurement results agree closely. Antenna meets or exceeds stated specifications. Parametric analysis and impedance matching are thorough. Radiation patterns and gain are well-characterized.' },
        { min: 27, max: 34, label: 'Good', description: 'Results are solid with acceptable simulation-measurement agreement. Key parameters (return loss, bandwidth, gain) are reported and meet specs with minor deviations.' },
        { min: 19, max: 26, label: 'Developing', description: 'Simulation results are presented but measurement validation is limited. Some specifications are not met or not clearly defined.' },
        { min: 0, max: 18, label: 'Insufficient', description: 'No measurement results or significant discrepancy between simulation and fabrication. Specifications are unmet.' },
      ]
    },
    {key:'application_and_presentation', label:'Application & Presentation', short:'Presentation', max:30, weight:30, color:'#F59E0B',
      customRubric: [
        { min: 27, max: 30, label: 'Excellent', description: 'Clear real-world application with a compelling use case (5G, IoT, biomedical, satellite, etc.). Poster is professional, visually clear, and the oral presentation demonstrates deep understanding.' },
        { min: 21, max: 26, label: 'Good', description: 'Application context is established. Presentation is organized and the team answers most questions correctly.' },
        { min: 13, max: 20, label: 'Developing', description: 'Application is mentioned but not developed. Presentation is adequate but lacks depth in Q&A.' },
        { min: 0, max: 12, label: 'Insufficient', description: 'No clear application. Presentation is poorly prepared or the team cannot answer basic questions about their design.' },
      ]
    }
  ],
  [
    ['DC-1', 'Creativity'], ['DC-2', 'Technical Merit'], ['DC-3', 'Practical Application'], ['DC-4', 'Educational Value']
  ],
  [
    {crit:'creativity', outs:[{code:'DC-1',weight:0.7}, {code:'DC-4',weight:0.3}]},
    {crit:'technical_merit', outs:[{code:'DC-2',weight:0.8}, {code:'DC-3',weight:0.2}]},
    {crit:'application_and_presentation', outs:[{code:'DC-3',weight:0.5}, {code:'DC-4',weight:0.3}, {code:'DC-1',weight:0.2}]}
  ]
);

processOrgfw('CANSAT-2025', 'Mission Framework', '2025',
  [
    {key:'design_compliance', label:'Design Constraints Compliance', short:'Compliance', max:20, weight:20, color:'#6366F1',
      customRubric: [
        { min: 18, max: 20, label: 'Excellent', description: 'CanSat fits within the 350 ml volume and 500 g mass budget. All structural, electrical, and communications constraints are fully met with documented margin analysis.' },
        { min: 14, max: 17, label: 'Good', description: 'Constraints are met with minor deviations. Mass or volume budget is tight but within tolerance.' },
        { min: 10, max: 13, label: 'Developing', description: 'One or more constraints are marginally exceeded. Documentation does not clearly show compliance analysis.' },
        { min: 0, max: 9, label: 'Insufficient', description: 'Multiple constraints are violated or compliance documentation is missing.' },
      ]
    },
    {key:'mission_execution', label:'Mission Execution & Telemetry', short:'Mission', max:35, weight:35, color:'#EF4444',
      customRubric: [
        { min: 31, max: 35, label: 'Excellent', description: 'Primary and secondary missions are fully executed. Telemetry stream is continuous with no data gaps. Sensor readings are accurate and timestamped. Real-time ground station display is functional.' },
        { min: 24, max: 30, label: 'Good', description: 'Primary mission is completed successfully. Telemetry has minor gaps (<5%). Secondary mission partially demonstrated.' },
        { min: 17, max: 23, label: 'Developing', description: 'Primary mission partially completed. Telemetry has significant gaps or sensor accuracy is questionable.' },
        { min: 0, max: 16, label: 'Insufficient', description: 'Mission fails to execute. Telemetry is non-functional or unreliable.' },
      ]
    },
    {key:'data_and_documentation', label:'Data Analysis & Documentation', short:'Data', max:25, weight:25, color:'#3B82F6',
      customRubric: [
        { min: 22, max: 25, label: 'Excellent', description: 'Flight data is thoroughly analyzed with appropriate statistical methods. Graphs are clear and well-labelled. Post-flight report compares expected vs. actual performance with root-cause analysis of anomalies.' },
        { min: 17, max: 21, label: 'Good', description: 'Data analysis is competent with clear visualizations. Post-flight report addresses key findings with minor gaps in anomaly discussion.' },
        { min: 12, max: 16, label: 'Developing', description: 'Data is presented but analysis is shallow. Post-flight report lacks quantitative comparison or anomaly investigation.' },
        { min: 0, max: 11, label: 'Insufficient', description: 'Raw data dump with no meaningful analysis. Post-flight report is missing or superficial.' },
      ]
    },
    {key:'safety_and_recovery', label:'Safety & Recovery', short:'Safety', max:20, weight:20, color:'#10B981',
      customRubric: [
        { min: 18, max: 20, label: 'Excellent', description: 'CanSat is recovered intact with all safety mechanisms functioning. Descent rate is within specification. Parachute or recovery system deploys reliably. Team follows all range safety procedures.' },
        { min: 14, max: 17, label: 'Good', description: 'Recovery is successful with minor issues. Descent rate is close to spec. Safety procedures are mostly followed.' },
        { min: 10, max: 13, label: 'Developing', description: 'Recovery is partial or descent rate deviates significantly from spec. Safety procedures require reminders.' },
        { min: 0, max: 9, label: 'Insufficient', description: 'CanSat is lost or damaged. Recovery system fails. Safety violations observed.' },
      ]
    }
  ],
  [
    ['CS-1', 'Design Constraints Compliance'], ['CS-2', 'Primary Mission Execution'], ['CS-3', 'Descent Control and Recovery'],
    ['CS-4', 'Safety and Restrictions Compliance'], ['CS-5', 'Secondary Mission Originality'], ['CS-6', 'Data Analysis and Documentation Quality']
  ],
  [
    {crit:'design_compliance', outs:[{code:'CS-1',weight:0.7}, {code:'CS-4',weight:0.3}]},
    {crit:'mission_execution', outs:[{code:'CS-2',weight:0.5}, {code:'CS-5',weight:0.3}, {code:'CS-3',weight:0.2}]},
    {crit:'data_and_documentation', outs:[{code:'CS-6',weight:0.7}, {code:'CS-2',weight:0.3}]},
    {crit:'safety_and_recovery', outs:[{code:'CS-4',weight:0.5}, {code:'CS-3',weight:0.5}]}
  ]
);

out.push(`-- Frameworks`);
out.push(fws.join('\n')); out.push('');
out.push(`-- Framework Outcomes`);
out.push(fwOutcomes.join('\n')); out.push('');
out.push(`-- Framework Criteria`);
out.push(fwCriteria.join('\n')); out.push('');
out.push(`-- Framework Mappings`);
out.push(fwMaps.join('\n')); out.push('');

// PERIODS
out.push(`-- Periods and Snapshots`);
const periodData = [];

const orgPeriodsDef = {
  'TEDU-EE': [{name:'Spring 2026',s:'Spring',start:'2026-02-01',end:'2026-06-15'},{name:'Fall 2025',s:'Fall',start:'2025-09-01',end:'2025-12-20'},{name:'Spring 2025',s:'Spring',start:'2025-02-01',end:'2025-06-15'},{name:'Fall 2024',s:'Fall',start:'2024-09-01',end:'2025-01-15'}],
  'CMU-CS': [{name:'Spring 2026',s:'Spring',start:'2026-02-01',end:'2026-06-15'},{name:'Fall 2025',s:'Fall',start:'2025-09-01',end:'2025-12-20'},{name:'Spring 2025',s:'Spring',start:'2025-02-01',end:'2025-06-15'},{name:'Fall 2024',s:'Fall',start:'2024-09-01',end:'2025-01-15'}],
  'TEKNOFEST': [{name:'2026 Season',s:'NULL',start:'2026-06-01',end:'2026-08-15'},{name:'2025 Season',s:'NULL',start:'2025-06-01',end:'2025-08-15'},{name:'2024 Season',s:'NULL',start:'2024-06-01',end:'2024-08-15'}],
  'TUBITAK-2204A': [{name:'2026 Competition',s:'NULL',start:'2026-06-01',end:'2026-08-15'},{name:'2025 Competition',s:'NULL',start:'2025-06-01',end:'2025-08-15'},{name:'2024 Competition',s:'NULL',start:'2024-06-01',end:'2024-08-15'}],
  'IEEE-APSSDC': [{name:'2026 Contest',s:'NULL',start:'2026-06-01',end:'2026-08-15'},{name:'2025 Contest',s:'NULL',start:'2025-06-01',end:'2025-08-15'},{name:'2024 Contest',s:'NULL',start:'2024-06-01',end:'2024-08-15'}],
  'CANSAT-2025': [{name:'2026 Season',s:'Spring',start:'2026-06-01',end:'2026-08-15'},{name:'2025 Season',s:'Spring',start:'2025-06-01',end:'2025-08-15'},{name:'2024 Season',s:'Spring',start:'2024-06-01',end:'2024-08-15'}]
};

orgs.forEach(o => {
  const fwId = uuid('fw-' + o.code);
  const defs = orgPeriodsDef[o.code] || [];
  defs.forEach((d, idx) => {
    const isCurrent = idx === 0;
    const isLocked = !isCurrent;
    const pId = uuid(`period-${o.code}-${idx}`);
    const poster = `DATE '${d.end}' - integer '14'`;
    const frozen = isCurrent ? `('${d.start}'::timestamp + interval '1 day')` : `('${d.start}'::timestamp)`;
    const tstamp = `timestamp '${d.start}' + interval '2 days'`;
    
    let sn = d.s === 'NULL' ? 'NULL' : `'${d.s}'`;
    
    out.push(`INSERT INTO periods (id, organization_id, framework_id, name, season, is_current, is_locked, is_visible, poster_date, snapshot_frozen_at, updated_at) VALUES ('${pId}', '${o.id}', '${fwId}', '${escapeSql(d.name)}', ${sn}, ${isCurrent}, ${isLocked}, true, ${poster}, ${frozen}, ${tstamp}) ON CONFLICT DO NOTHING;`);
    
    const pcMap = {};
    o.criteriaData.forEach(c => {
      const pcId = uuid(`pcrit-${pId}-${c.key}`);
      pcMap[c.id] = pcId;
      const rubricJson = c.customRubric ? JSON.stringify(c.customRubric).replace(/'/g, "''") : parseRubric(c.max);
      
      // Snapshot isolation: older periods may have used slightly different criteria wording
      let cLabel = c.label;
      if (idx === 1) {
        // Previous period: minor wording updates (e.g. renamed for clarity)
        cLabel = cLabel.replace('Communication & Documentation', 'Communication Skills')
                       .replace('Application & Presentation', 'Application & Demo')
                       .replace('Team Execution & Presentation', 'Team Coordination')
                       .replace('Impact & Presentation', 'Presentation & Impact');
      }
      if (idx === 2) {
        // Two periods ago: older naming convention (v1 labels)
        cLabel = cLabel.replace('Problem Solving & Analysis', 'Analytical Thinking')
                       .replace('System Design & Architecture', 'Software Architecture')
                       .replace('Creativity & Innovation', 'Innovation')
                       .replace('Design Constraints Compliance', 'Constraints Verification')
                       .replace('Mission Execution & Telemetry', 'Flight Performance');
      }

      out.push(`INSERT INTO period_criteria (id, period_id, source_criterion_id, key, label, short_label, max_score, weight, color, rubric_bands, sort_order) VALUES ('${pcId}', '${pId}', '${c.id}', '${c.key}', '${escapeSql(cLabel)}', '${escapeSql(c.short)}', ${c.max}, ${c.weight}, '${c.color}', '${rubricJson}', ${c.sortOrder}) ON CONFLICT DO NOTHING;`);
    });

    const poMap = {};
    o.outcomesData.forEach(oc => {
      const poId = uuid(`pout-${pId}-${oc.code}`);
      poMap[oc.id] = poId;
      out.push(`INSERT INTO period_outcomes (id, period_id, source_outcome_id, code, label, sort_order) VALUES ('${poId}', '${pId}', '${oc.id}', '${oc.code}', '${escapeSql(oc.label)}', ${oc.sortOrder}) ON CONFLICT DO NOTHING;`);
    });

    o.mapsData.forEach(m => {
      const pmId = uuid(`pmap-${pId}-${m.cId}-${m.oId}`);
      const pcId = pcMap[m.cId];
      const poId = poMap[m.oId];
      out.push(`INSERT INTO period_criterion_outcome_maps (id, period_id, period_criterion_id, period_outcome_id, weight) VALUES ('${pmId}', '${pId}', '${pcId}', '${poId}', ${m.weight}) ON CONFLICT DO NOTHING;`);
    });
    
    periodData.push({ id: pId, org: o.code, isCur: isCurrent, histIdx: idx, start:d.start, name: d.name });
  });
});
out.push('');

// PROJECTS
out.push(`-- Projects`);
const teduProjects = [
  {t: 'FPGA-Based Real-Time Signal Processing for 5G NR', a:'Prof. Turgut Ercan', a_aff: 'TED University, EE', arch: 'star'},
  {t: 'Low-Power IoT Sensor Network for Smart Agriculture', a:'Dr. Ece Aydoğan', a_aff: 'TED University, EE', arch: 'solid'},
  {t: 'Autonomous Drone Navigation with LiDAR SLAM', a:'Prof. Cengiz Yalın', a_aff: 'TED University, EE', arch: 'highvar'},
  {t: 'GaN Power Amplifier Design for Sub-6 GHz 5G', a:'Dr. Aylin Seçkin', a_aff: 'TED University, EE', arch: 'tech_strong_comm_weak'},
  {t: 'Edge AI Accelerator on RISC-V for Anomaly Detection', a:'Prof. Tarık Özmen', a_aff: 'TED University, EE', arch: 'borderline'},
];

// Per-period project pools for TEDU-EE historical — each period gets unique titles
const teduHistProjects = {
  1: ['Wearable ECG Monitor with BLE Connectivity', 'MIMO Antenna Design for Indoor 5G Coverage', 'Solar-Powered Environmental Monitoring Station', 'Robotic Arm Control via EMG Signals', 'Smart Grid Fault Detection Using Phasor Data'],
  2: ['Visible Light Communication Transceiver Prototype', 'FPGA-Based Audio Effects Processor', 'Quadcopter Stabilization with Kalman Filtering', 'Thermal Imaging for Industrial Predictive Maintenance'],
  3: ['DC Motor Speed Control with Fuzzy Logic', 'PCB Design for Portable Oscilloscope', 'Home Energy Management Dashboard'],
};

// Per-period project pools for CMU-CS — unique per semester
const cmuProjectPools = {
  0: ['GPU-Accelerated LLM Inference Engine', 'Privacy-Preserving Federated Learning Framework', 'Distributed File System with Raft Consensus', 'Autonomous Intersection Management via Multi-Agent RL', 'Real-Time Gesture Recognition Pipeline', 'Verifiable Computation with Zero-Knowledge Proofs'],
  1: ['Scalable Graph Neural Network for Drug Discovery', 'End-to-End Encrypted Group Messaging Protocol', 'Kubernetes Autoscaler with Predictive Load Modeling', 'Neural Radiance Fields for Indoor Mapping'],
  2: ['Compiler Optimization Pass for WebAssembly', 'Peer-to-Peer Video Streaming with Adaptive Bitrate', 'Automated Vulnerability Detection with Static Analysis'],
  3: ['Cache-Oblivious B-Tree Implementation', 'Differentially Private Query Engine'],
};

// Per-period pools for TEKNOFEST
const teknofestProjectPools = {
  0: ['Otonom Sürü İHA Takip ve Koordinasyon Sistemi', 'Yüksek İrtifa Hibrit Roket Motoru Tasarımı', 'Otonom Sualtı Aracı ile Deniz Tabanı Haritalama', 'VTOL Sabit Kanatlı Kargo Dronu Prototipi', 'Radar Absorban Kompozit Kaplama Geliştirme'],
  1: ['Tarımsal İlaçlama için Çoklu Drone Filosu', 'Sıvı Yakıtlı Model Roket ile Yükseklik Rekoru', 'Otonom Yüzey Aracı ile Su Kalitesi İzleme', 'Dikey İniş Kalkış Teslimat Dronu'],
  2: ['Güneş Enerjili Sabit Kanatlı İHA Dayanıklılık Testi', 'Katı Yakıtlı Roket Motor Test Düzeneği', 'Sualtı Akustik Haberleşme Modemi'],
};

// Per-period pools for TUBITAK
const tubitakProjectPools = {
  0: ['Yapay Zeka Destekli Erken Orman Yangını Tespiti', 'Tarımsal Atıklardan Ağır Metal Filtreleme Membranı', 'Giyilebilir Postür Düzeltme Sensörü ve Mobil Uygulaması', 'Mikroalg Biyoreaktörü ile Atmosferik CO₂ Yakalama'],
  1: ['Arı Kolonisi Sağlığı İzleme Sistemi', 'Biyobozunur Plastik Üretiminde Mısır Nişastası Optimizasyonu', 'Toprak Neminin Yapay Zeka ile Tahmin Edilmesi'],
  2: ['Güneş Paneli Verimlilik Artırma Kaplaması', 'Su Arıtmada Doğal Zeolitlerin Kullanımı'],
};

// Per-period pools for IEEE
const ieeeProjectPools = {
  0: ['Phased Array Antenna for 28 GHz mmWave 5G', 'Wearable UHF RFID Tag Antenna for Patient Tracking', 'Dual-Band Circularly Polarized Microstrip Patch for GPS/GLONASS', 'Metamaterial Absorber for Radar Cross-Section Reduction'],
  1: ['Reconfigurable Frequency-Selective Surface for 5G Shielding', 'Compact MIMO Antenna for Sub-6 GHz Handsets', 'Substrate-Integrated Waveguide Filter for Ka-Band'],
  2: ['Dielectric Resonator Antenna for Millimeter-Wave Imaging', 'Flexible Inkjet-Printed Antenna for Wearable IoT'],
};

// Per-period pools for CanSat
const cansatProjectPools = {
  0: ['Autogyro Descent and Precision Landing System', 'Dual-Redundant Telemetry with LoRa Failover', 'Multi-Sensor Atmospheric Profiling Payload', 'Deployable Aerobrake Heat Shield Demonstrator'],
  1: ['Parafoil Guided Recovery with GPS Waypoint Navigation', 'Solar-Powered Secondary Mission: UV Index Mapping', 'Deployable Boom Magnetometer Suite'],
  2: ['Maple-Seed Inspired Passive Descent Vehicle', 'Ground Station with Real-Time 3D Trajectory Visualization'],
};

// Separate advisor pools per org — never overlap with student names
const orgAdvisors = {
  'TEDU-EE': [
    {n:'Prof. Turgut Ercan', aff:'TED University, EE'}, {n:'Dr. Ece Aydoğan', aff:'TED University, EE'},
    {n:'Prof. Cengiz Yalın', aff:'TED University, EE'}, {n:'Dr. Aylin Seçkin', aff:'TED University, EE'},
    {n:'Prof. Tarık Özmen', aff:'TED University, EE'}, {n:'Dr. Seda Bayraktar', aff:'TED University, EE'},
  ],
  'CMU-CS': [
    {n:'Prof. David Patterson', aff:'Carnegie Mellon University, SCS'}, {n:'Dr. Lisa Chen', aff:'Carnegie Mellon University, SCS'},
    {n:'Prof. Robert Singh', aff:'Carnegie Mellon University, ECE'}, {n:'Dr. Amanda Torres', aff:'Carnegie Mellon University, LTI'},
    {n:'Prof. Michael Hoffman', aff:'Carnegie Mellon University, ISR'}, {n:'Dr. Karen White', aff:'Carnegie Mellon University, SCS'},
  ],
  'TEKNOFEST': [
    {n:'Prof. Serhat Öztürk', aff:'İTÜ, Uçak Mühendisliği'}, {n:'Dr. Fatma Korkmaz', aff:'ODTÜ, Havacılık Mühendisliği'},
    {n:'Prof. Murat Yıldız', aff:'İTÜ, Makina Mühendisliği'}, {n:'Dr. Zehra Aksoy', aff:'Yıldız Teknik, Mekatronik'},
    {n:'Prof. Hakan Güneş', aff:'Boğaziçi Üniversitesi, Elektrik Mühendisliği'},
  ],
  'TUBITAK-2204A': [
    {n:'Dr. Merve Yıldırım', aff:'Ankara Fen Lisesi'}, {n:'Selin Karadeniz', aff:'İstanbul Atatürk Fen Lisesi'},
    {n:'Ahmet Çelik', aff:'İzmir Fen Lisesi'}, {n:'Dr. Burcu Eren', aff:'ODTÜ Geliştirme Vakfı Lisesi'},
  ],
  'IEEE-APSSDC': [
    {n:'Prof. Harold Kim', aff:'University of Michigan, ECE'}, {n:'Dr. Sarah Novak', aff:'Georgia Tech, ECE'},
    {n:'Prof. Wei Zhang', aff:'UCLA, Electrical Engineering'}, {n:'Dr. Anita Patel', aff:'Purdue University, ECE'},
  ],
  'CANSAT-2025': [
    {n:'Prof. Richard Kline', aff:'Virginia Tech, Aerospace Engineering'}, {n:'Dr. Samantha Ford', aff:'MIT, AeroAstro'},
    {n:'Prof. Douglas Park', aff:'University of Colorado, Aerospace Sciences'}, {n:'Dr. Yuki Tanaka', aff:'Caltech, GALCIT'},
  ],
};

const namesTr = [
  'Tolga Erim', 'Melis Kavak', 'Ozan Çelebi', 'Ezgi Doruk', 'Caner Turgut', 'Aslı Tezcan', 'Berk Gündüz', 'Ceyda Vural', 'Korhan Alkan', 'Sinem Uslu',
  'Arda Keçeci', 'Zeynep Gül', 'Baran Tekin', 'Kübra Şen', 'Mert Çakır', 'İrem Demirci', 'Hakan Kurt', 'Elif Yılmaz', 'Sinan Koç', 'Ece Yıldırım',
  'Yiğit Polat', 'Damla Kılıç', 'Kaan Avcı', 'Büşra Doğan', 'Alperen Turan', 'Rüya Işık', 'Emre Baş', 'Gizem Aksoy', 'Serkan Taşkın', 'Deniz Ünal',
  'Onur Çelik', 'Selin Akay', 'Burak Aslan', 'Beren Yücel', 'Kerem Arıcan', 'Esra Kaya', 'Umut Şahin', 'Ceren Erdoğan', 'Eren Güler', 'Tuğçe Can',
  'Doğukan Arslan', 'Nisa Öztürk', 'Barış Yıldız', 'Cansu Demir', 'Furkan Polat', 'Hazal Koç', 'Tuna Bakır', 'Merve Karaca', 'Alp Sönmez', 'Defne Çetin',
  'Oğuzhan Kara', 'Pelin Aydın', 'Efe Güneş', 'Nehir Tosun', 'Berke Şimşek', 'İlayda Başaran', 'Doruk Acar', 'Cemre Uçar', 'Taylan Ergin', 'Yağmur Tunç',
  'Adem Yılmaztürk', 'Sevval Kaplan', 'Cenk Duman', 'Beyza Güler', 'Batuhan Koçak', 'Dilan Aktaş', 'Kutay Erdal', 'Betül Sezer', 'Çağrı Özkan', 'Zehra Kurt',
  'Görkem Taş', 'Eylül Özdemir', 'Volkan Arı', 'Sude Bulut', 'Alihan Topçu', 'Irmak Genç', 'Oğuz Balcı', 'Havva Keskin', 'Atakan Yavuz', 'Melisa Tuncer',
];
const namesEn = [
  'Elias Boyd', 'Clara Dawson', 'Miles Cunningham', 'Sophie Clarke', 'Nolan Davies', 'Maya Jenkins', 'Julian Hayes', 'Eva Harding', 'Leo Gallagher', 'Tessa Rowan',
  'Adam Bennett', 'Hazel Foster', 'Cole Harrison', 'Lucy Brooks', 'Dylan Reed', 'Aurora Price', 'Ethan Ward', 'Stella Myers', 'Connor Ross', 'Zoe Powell',
  'Lucas Sullivan', 'Grace Kelly', 'Mason Bell', 'Ruby Murphy', 'Logan Bailey', 'Lily Cooper', 'Caleb Richardson', 'Mia Howard', 'Nathan Cox', 'Chloe Ward',
  'Isaac Perez', 'Emma Peterson', 'Owen Gray', 'Avery James', 'Wyatt Watson', 'Ella Brooks', 'Jack Kelly', 'Aria Sanders', 'Ryan Price', 'Scarlett Wood',
  'Liam Fletcher', 'Olivia Chen', 'Noah Patterson', 'Amelia Wright', 'Henry Torres', 'Charlotte Kim', 'Samuel Rivera', 'Harper Morgan', 'Benjamin Cruz', 'Abigail Reeves',
  'Theodore Grant', 'Eleanor Marsh', 'Sebastian Cross', 'Victoria Hale', 'Daniel Frost', 'Penelope Blake', 'Alexander Dunn', 'Layla Stone', 'Matthew Doyle', 'Isla Webb',
  'James Thornton', 'Violet Keane', 'Andrew Holden', 'Naomi Swift', 'Patrick Rowe', 'Sophia Linden', 'Christopher Vale', 'Alice Brennan', 'Gabriel Locke', 'Hannah Pratt',
  'Dominic Hurst', 'Madeline Ford', 'Vincent Crane', 'Piper York', 'Marcus Shore', 'Sienna West', 'Oscar Quinn', 'Jade Sinclair', 'Felix Palmer', 'Willow Drake',
];

function genMembers(count, lang) {
  let list = lang === 'tr' ? [...namesTr] : [...namesEn];
  list.sort(() => random() - 0.5);
  return JSON.stringify(list.slice(0, count).map((n, i) => ({name: n, order: i+1}))).replace(/'/g, "''");
}

// Lookup table: org → per-period project pool
const orgProjectPools = {
  'CMU-CS': cmuProjectPools,
  'TEKNOFEST': teknofestProjectPools,
  'TUBITAK-2204A': tubitakProjectPools,
  'IEEE-APSSDC': ieeeProjectPools,
  'CANSAT-2025': cansatProjectPools,
};

let projList = [];
periodData.forEach(pd => {
  let count = 0;
  let lang = 'tr';
  if (pd.org === 'TEDU-EE') { count = pd.isCur ? 5 : (pd.histIdx===1 ? 5 : (pd.histIdx===2 ? 4 : 3)); }
  else if (pd.org === 'CMU-CS') { count = pd.isCur ? 6 : (pd.histIdx===1 ? 4 : (pd.histIdx===2 ? 3 : 2)); lang='en'; }
  else if (pd.org === 'TEKNOFEST') { count = pd.isCur ? 5 : (pd.histIdx===1 ? 4 : (pd.histIdx===2 ? 3 : 2)); }
  else { count = pd.isCur ? 4 : (pd.histIdx===1 ? 3 : (pd.histIdx===2 ? 2 : 2)); lang = (pd.org.includes('CANSAT') || pd.org.includes('IEEE')) ? 'en' : 'tr'; }

  // Resolve advisor pool for this org
  const advisors = orgAdvisors[pd.org] || [];

  for(let i=0; i<count; i++) {
    const pjId = uuid(`proj-${pd.id}-${i}`);
    let title = '';
    let arch = pick(['star', 'solid', 'average', 'weak_tech_strong_team', 'borderline']);

    // Default advisor from dedicated pool
    const advisor = advisors[i % advisors.length];
    let aName = advisor.n;
    let aAff = advisor.aff;

    if (pd.org === 'TEDU-EE' && pd.isCur) {
      title = teduProjects[i].t;
      arch = teduProjects[i].arch;
      aName = teduProjects[i].a;
      aAff = teduProjects[i].a_aff;
    } else if (pd.org === 'TEDU-EE') {
      const pool = teduHistProjects[pd.histIdx] || teduHistProjects[3] || [];
      title = pool[i % pool.length];
    } else {
      // All other orgs use per-period project pools
      const pools = orgProjectPools[pd.org];
      const pool = pools ? (pools[pd.histIdx] || pools[0]) : [];
      title = pool[i % pool.length];
    }

    let mCount = randInt(3, 4);
    let mem = genMembers(mCount, lang);
    let no = i+1;
    out.push(`INSERT INTO projects (id, period_id, title, project_no, members, advisor_name, advisor_affiliation) VALUES ('${pjId}', '${pd.id}', '${escapeSql(title)}', ${no}, '${mem}', '${escapeSql(aName)}', '${escapeSql(aAff)}') ON CONFLICT DO NOTHING;`);
    projList.push({id: pjId, pId: pd.id, org: pd.org, isCur: pd.isCur, arch, title});
  }
});
out.push('');

// JURORS
out.push(`-- Jurors and Auth`);

function jurorEmail(name) {
  return name.replace(/^(Prof\.|Dr\.|Col\.)\s*/i, '').trim().toLowerCase()
    .replace(/\s+/g, '.').replace(/[şŞ]/g, 's').replace(/[çÇ]/g, 'c')
    .replace(/[ğĞ]/g, 'g').replace(/[ıİ]/g, 'i').replace(/[öÖ]/g, 'o')
    .replace(/[üÜ]/g, 'u').replace(/[â]/g, 'a') + '@vera-eval.app';
}

const orgJurors = {
  'TEDU-EE': [
    {n: 'Prof. Cihan Akpınar', aff: 'Sabancı University, EE'},
    {n: 'Dr. Aslıhan Koçak', aff: 'Ohio State University, ECE'},
    {n: 'Prof. Ferit Atasoy', aff: 'METU, Electrical & Electronics Engineering'},
    {n: 'Dr. Pınar Dalkılıç', aff: 'İstanbul Technical University, Computer Engineering'},
    {n: 'Engin Boztepe', aff: 'Aselsan, RF Systems Division'},
    {n: 'Dr. Serap Gündoğdu', aff: 'TÜBİTAK BİLGEM'},
    {n: 'Prof. Orhan Sezgin', aff: 'Bilkent University, Electrical Engineering'},
    {n: 'Yasin Erimbaş', aff: 'Türk Telekom, R&D Center'},
    {n: 'Dr. Nihan Ersoy', aff: 'İstanbul Technical University, Electronics Engineering'},
    {n: 'Dr. Alper Kılıç', aff: 'Hacettepe University, Electrical Engineering'},
  ],
  'CMU-CS': [
    {n: 'Dr. Thomas Albright', aff: 'MIT, Computer Science & AI Lab'},
    {n: 'Prof. Simon Caldwell', aff: 'Stanford University, Computer Science'},
    {n: 'Nina Prescott', aff: 'Google Research, Mountain View'},
    {n: 'Wesley Dalton', aff: 'Microsoft Research, Redmond'},
    {n: 'Dr. Sofia Lang', aff: 'UC Berkeley, EECS'},
    {n: 'Victor Sutton', aff: 'Meta AI, Menlo Park'},
    {n: 'Fiona Mercer', aff: 'Carnegie Mellon University, Robotics Institute'},
  ],
  'TEKNOFEST': [
    {n: 'Prof. Kemal Özdemir', aff: 'İTÜ, Havacılık ve Uzay Mühendisliği'},
    {n: 'Dr. Eda Sarıgül', aff: 'TUSAŞ (TAI), Ar-Ge Merkezi'},
    {n: 'Onur Yalçın', aff: 'Baykar Teknoloji, İHA Sistemleri'},
    {n: 'Prof. Buse Karagöz', aff: 'ODTÜ, Makina Mühendisliği'},
    {n: 'Cemil Demirtaş', aff: 'Roketsan, Güdüm Sistemleri'},
    {n: 'Dr. Aylin Çevik', aff: 'TÜBİTAK SAGE, Savunma Teknolojileri'},
  ],
  'TUBITAK-2204A': [
    {n: 'Prof. Hasan Yüksel', aff: 'Boğaziçi Üniversitesi, Fizik Bölümü'},
    {n: 'Dr. Elif Aydın', aff: 'Hacettepe Üniversitesi, Biyoloji Bölümü'},
    {n: 'Prof. Okan Birdal', aff: 'Koç Üniversitesi, Kimya Bölümü'},
    {n: 'Dr. Sevgi Toprak', aff: 'Ankara Üniversitesi, Fen Bilimleri Enstitüsü'},
    {n: 'Prof. Burak Çetin', aff: 'ODTÜ, Matematik Bölümü'},
  ],
  'IEEE-APSSDC': [
    {n: 'Prof. Raymond Chen', aff: 'University of Michigan, Electrical Engineering'},
    {n: 'Dr. Catherine Liu', aff: 'Georgia Institute of Technology, ECE'},
    {n: 'Prof. Kenneth Walsh', aff: 'University of Illinois Urbana-Champaign, ECE'},
    {n: 'Dr. Priya Raghavan', aff: 'Purdue University, Electrical & Computer Engineering'},
  ],
  'CANSAT-2025': [
    {n: 'Dr. James Whitfield', aff: 'Virginia Tech, Aerospace Engineering'},
    {n: 'Prof. Laura Henderson', aff: 'University of Colorado Boulder, Aerospace Sciences'},
    {n: 'Col. Robert Drake', aff: 'US Air Force Academy, Astronautics'},
    {n: 'Dr. Megan Yoshida', aff: 'NASA Goddard Space Flight Center'},
  ],
};

const palette = ['#F59E0B', '#3B82F6', '#8B5CF6', '#EC4899', '#10B981', '#EF4444', '#6366F1', '#14B8A6', '#F97316', '#A855F7'];

let jurorIdList = [];
orgs.forEach(o => {
  const items = orgJurors[o.code] || [];
  items.forEach((j, i) => {
    const jId = uuid(`juror-${o.code}-${i}`);
    const color = palette[i % palette.length];
    const email = jurorEmail(j.n);
    out.push(`INSERT INTO jurors (id, organization_id, juror_name, affiliation, email, avatar_color) VALUES ('${jId}', '${o.id}', '${escapeSql(j.n)}', '${escapeSql(j.aff)}', '${email}', '${color}') ON CONFLICT DO NOTHING;`);
    jurorIdList.push({id: jId, org: o.code, n: j.n, idx: i});
  });
});

// Pre-computed hash of '1234'
const pinHash = "$2a$06$D1E3X/QGg9sM4W0.A3vQG.n9v6p0y5NlKJ/K6W9fHq7.HkH9n.AWe";

let authList = [];
periodData.forEach(pd => {
  let pJurors = jurorIdList.filter(j => j.org === pd.org);
  if(pd.histIdx === 3) pJurors = []; // Skip deep history scoring entirely
  else if(pd.histIdx === 2) pJurors = pJurors.slice(0, 1);
  else if(pd.histIdx === 1) pJurors = pJurors.slice(0, 2);
  
  pJurors.forEach((j, jix) => {
    let statusId = jix; // We map index to a semantic workflow status
    if (jix >= 5) {
      statusId = random() > 0.3 ? 0 : 1; // Heavy on Completed/InProgress for rest
    }
    
    // Status Semantic IDs:
    // 0: Completed, 1: InProgress, 2: Ready, 3: NotStarted, 4: Editing
    let semanticState = 'Completed';
    if (statusId === 1) semanticState = 'InProgress';
    else if (statusId === 2) semanticState = 'Ready';
    else if (statusId === 3) semanticState = 'NotStarted';
    else if (statusId === 4) semanticState = 'Editing';

    let authObj = { jId: j.id, pId: pd.id, org: pd.org, isCur: pd.isCur, active:true, locked:false, blocked:false, semanticState, name: j.n };
    let q = `INSERT INTO juror_period_auth (juror_id, period_id, pin_hash`;
    let vals = `VALUES ('${j.id}', '${pd.id}', '${pinHash}'`;
    
    if (semanticState === 'Completed' || semanticState === 'Editing') {
      let submitTime = pd.isCur ? `${BASE_TIME} - interval '${randInt(1,5)} hours'` : `timestamp '${pd.start}' + interval '10 days'`;
      q += `, final_submitted_at`; vals += `, ${submitTime}`;
    }
    
    if (semanticState === 'Editing') {
       q += `, edit_enabled, edit_reason, edit_expires_at`; vals += `, true, 'Late submission due to connectivity issue', ${BASE_TIME} + interval '24 hours'`;
    }

    if (pd.isCur && pd.org === 'TEDU-EE' && jix === 8) {
      authObj.locked = true;
      q += `, failed_attempts, locked_until, locked_at`; vals += `, 3, ${BASE_TIME} + interval '5 mins', ${BASE_TIME}`;
    }
    if (pd.isCur && pd.org === 'TEDU-EE' && jix === 9) {
       authObj.blocked = true;
       q += `, is_blocked`; vals += `, true`;
    }
    
    q += `) ${vals}) ON CONFLICT DO NOTHING;`;
    out.push(q);
    authList.push(authObj);
  });
});
out.push('');

// SCORES & ITEMS
out.push(`-- Scoring`);

const scoreCommentsByArch = {
  star: [
    'Outstanding work across all criteria. One of the strongest presentations of the day.',
    'Excellent project — deep technical understanding and very polished delivery.',
    'Impressive depth combined with clear communication. Top marks well deserved.',
    'This team stood out. Well-structured, well-presented, and technically sound.',
    'Exceptional overall. The prototype was working flawlessly during the demo.',
  ],
  solid: [
    'Good solid work. A few rough edges but a strong submission overall.',
    'Competent presentation. The technical implementation is well done.',
    'Well-prepared team. Minor improvements in delivery would push this to the top tier.',
    'Reliable work. The written report was particularly well organized.',
    'Solid engineering. The team handled the Q&A confidently.',
  ],
  highvar: [
    'Interesting project with high peaks but some inconsistency in the presentation.',
    'Strong technical ideas; the team would benefit from more practice presenting.',
    'The concept is excellent — execution was uneven across team members.',
    'Creative approach. Some criteria were handled much better than others.',
    'Promising work, but the quality varied significantly between sections.',
  ],
  tech_strong_comm_weak: [
    'Technically impressive, but the oral presentation needs improvement.',
    'The implementation is solid; the report and slides need more clarity.',
    'Strong engineering work. Communication skills could be developed further.',
    'Great technical results. The team should work on structuring their explanations.',
    'Solid system, but the team struggled to convey the significance of their work.',
  ],
  weak_tech_strong_team: [
    'Well-organized team with clear delivery, but technical depth was limited.',
    'Good teamwork and communication. The technical implementation needs more rigor.',
    'Very professional delivery; the underlying solution needs further development.',
    'Excellent presentation skills. The system itself has room for improvement.',
    'The team presented confidently but the technical contributions were thin.',
  ],
  borderline: [
    'The project meets minimum requirements but could use further development.',
    'Some promising ideas but both execution and presentation need work.',
    'Average performance overall. Needs stronger technical grounding.',
    'The team showed effort but the results were not convincing across all criteria.',
    'A fair attempt. Significant improvements needed before this is production-ready.',
  ],
  wellrounded: [
    'Consistent quality across all criteria. A well-balanced team effort.',
    'No weak spots — every section was handled with care and competence.',
    'The team delivered evenly strong work. Very balanced submission.',
    'Solid across the board. Each member clearly contributed.',
    'Well-rounded performance. Nothing outstanding but nothing lacking either.',
  ],
  strong_late: [
    'The technical results are impressive, though the presentation felt rushed.',
    'Clearly improved over the semester — the final demo was much stronger than the report.',
    'Strong engineering output. The written documentation didn\'t fully reflect the quality of the work.',
    'The prototype worked well; the team should invest more time in communication next time.',
    'Late bloomer — the technical depth is there but delivery needs polish.',
  ],
  partial: [
    'The project appears incomplete. Several sections were missing or underdeveloped.',
    'Limited scope of work presented. Hard to evaluate fully.',
    'Only a subset of the expected deliverables was demonstrated.',
    'The team ran out of time. What was shown was acceptable but insufficient.',
    'Partial submission — the foundation is there but execution fell short.',
  ],
  average: [
    'Reasonable effort. Some areas need more polish.',
    'The project addresses an interesting problem with adequate execution.',
    'Middle-of-the-pack performance. Nothing particularly strong or weak.',
    'Adequate work overall. Meets expectations without exceeding them.',
    'A fair submission. The team met the basic requirements.',
  ],
};

authList.forEach(auth => {
  if (auth.blocked || auth.locked) return;
  if (auth.semanticState === 'Ready' || auth.semanticState === 'NotStarted') return;

  const myProjs = projList.filter(p => p.pId === auth.pId);
  const totalMyProjs = myProjs.length;
  let targetCount = totalMyProjs;
  
  if (auth.semanticState === 'InProgress') {
    targetCount = Math.floor(totalMyProjs * 0.6); // ~60% coverage
    if (targetCount === 0 && totalMyProjs > 0) targetCount = 1;
  }
  
  let scoredCount = 0;
  myProjs.forEach((proj, pIx) => {
    if (scoredCount >= targetCount) return;

    const o = orgs.find(x => x.code === auth.org);
    const crits = o.criteriaData;
    let itemsCount = crits.length;
    
    // Semantic Status Logic:
    // If juror is InProgress, we limit the number of projects they have score sheets for (targetCount).
    // For the VERY LAST project in their limited set, we make it "Partial" (half criteria).
    let itemsToScore = itemsCount;
    let ssStatus = 'submitted';
    
    if (auth.semanticState === 'InProgress' && scoredCount === targetCount - 1) {
      itemsToScore = Math.floor(itemsCount * 0.5); 
      if (itemsToScore === 0 && itemsCount > 0) itemsToScore = 1;
      ssStatus = 'in_progress';
    }

    let ssId = uuid(`ss-${auth.jId}-${proj.id}`);
    let sst = `${BASE_TIME} - interval '${randInt(1, 48)} hours'`;

    if (!auth.isCur) {
      const pd = periodData.find(x => x.id === auth.pId);
      sst = `timestamp '${pd.start}' + interval '${randInt(2,10)} days'`;
    }

    let ssComment = 'NULL';
    if (ssStatus === 'submitted' && random() < 0.55) {
      const pool = scoreCommentsByArch[proj.arch] || defaultComments;
      ssComment = `'${escapeSql(pick(pool))}'`;
    }

    out.push(`
    INSERT INTO score_sheets (id, period_id, project_id, juror_id, status, comment, started_at, last_activity_at)
    VALUES ('${ssId}', '${auth.pId}', '${proj.id}', '${auth.jId}', '${ssStatus}', ${ssComment}, ${sst} - interval '30 mins', ${sst})
    ON CONFLICT DO NOTHING;
    `);
    
    let scoredItems = 0;
    crits.forEach((c) => {
      if (scoredItems >= itemsToScore) return;
      scoredItems++;

      let s = c.max;
      if(proj.arch === 'star') s = Math.floor(c.max * randInt(88,98)/100);
      else if(proj.arch === 'solid') s = Math.floor(c.max * randInt(74,85)/100);
      else if(proj.arch === 'wellrounded') s = Math.floor(c.max * randInt(78,88)/100);
      else if(proj.arch === 'strong_late') {
        // Started weak, finished strong — technical high, delivery/written moderate
        if(c.key === 'delivery' || c.key === 'design' || c.key === 'communication') s = Math.floor(c.max * randInt(68,78)/100);
        else s = Math.floor(c.max * randInt(82,92)/100);
      } else if(proj.arch === 'partial') {
        // Incomplete — scored lower across the board
        s = Math.floor(c.max * randInt(55,70)/100);
      } else if(proj.arch === 'highvar') s = Math.floor(c.max * randInt(50,100)/100);
      else if(proj.arch === 'tech_strong_comm_weak') {
        if(c.key === 'delivery' || c.key === 'communication' || c.key === 'design') s = Math.floor(c.max * 0.65);
        else s = Math.floor(c.max * 0.90);
      } else if(proj.arch === 'weak_tech_strong_team') {
        if(c.key === 'technical' || c.key === 'design' || c.key.includes('tech')) s = Math.floor(c.max * 0.55);
        else s = Math.floor(c.max * 0.85);
      } else if(proj.arch === 'borderline') s = Math.floor(c.max * randInt(58,72)/100);
      else if(proj.arch === 'average') s = Math.floor(c.max * randInt(65,78)/100);
      else s = Math.floor(c.max * randInt(65,85)/100);

      const siId = uuid(`ssi-${ssId}-${c.key}`);
      const pcId = uuid(`pcrit-${auth.pId}-${c.key}`);
      out.push(`
        INSERT INTO score_sheet_items (id, score_sheet_id, period_criterion_id, score_value)
        VALUES ('${siId}', '${ssId}', '${pcId}', ${s}) ON CONFLICT DO NOTHING;
      `);
    });
    
    scoredCount++;
  });
});
out.push('');

// TOKENS
out.push(`-- Entry Tokens (Hashed)`);
periodData.forEach(pd => {
  if(!pd.isCur) {
    let t_plain = uuid(`tok-exp-${pd.id}`);
    let t_hash = sha256(t_plain);
    let t_id = uuid(t_plain);
    out.push(`INSERT INTO entry_tokens (id, period_id, token_hash, is_revoked, expires_at) VALUES ('${t_id}', '${pd.id}', '${t_hash}', false, ${BASE_TIME} - interval '30 days') ON CONFLICT DO NOTHING;`);
  } else {
    out.push(`INSERT INTO entry_tokens (id, period_id, token_hash, is_revoked, expires_at) VALUES ('${uuid('tok1'+pd.id)}', '${pd.id}', '${sha256(uuid('t1'+pd.id))}', false, ${BASE_TIME} + interval '24 hours') ON CONFLICT DO NOTHING;`);
    out.push(`INSERT INTO entry_tokens (id, period_id, token_hash, is_revoked, expires_at) VALUES ('${uuid('tok2'+pd.id)}', '${pd.id}', '${sha256(uuid('t2'+pd.id))}', false, ${BASE_TIME} + interval '24 hours') ON CONFLICT DO NOTHING;`);
    out.push(`INSERT INTO entry_tokens (id, period_id, token_hash, is_revoked, expires_at, last_used_at) VALUES ('${uuid('tok3'+pd.id)}', '${pd.id}', '${sha256(uuid('t3'+pd.id))}', true, ${BASE_TIME} - interval '2 days', ${BASE_TIME} - interval '2.1 days') ON CONFLICT DO NOTHING;`);
  }
});

out.push('');


// AUDIT LOGS
out.push(`-- Audit Logs`);
let auditObjList = [];

const teduCurPeriod = periodData.find(pd => pd.org === 'TEDU-EE' && pd.isCur);
const teduCurProjs  = projList.filter(p => p.pId === teduCurPeriod.id);
const teduOrg       = orgs.find(x => x.code === 'TEDU-EE');

// 1. admin.create — all orgs
orgAdminIds.forEach((pId, i) => {
  const o = orgs[i % orgs.length];
  auditObjList.push({
    action: 'admin.create', resType: 'profile', resId: pId, orgId: o.id,
    details: '{"role":"org_admin"}', timeStr: `${BASE_TIME} - interval '50 days'`
  });
});

// 2. application.approved / rejected
orgAppIds.forEach(oa => {
  const o = orgs.find(x => x.code === oa.org);
  const status = appStatuses[orgs.indexOf(o)];
  if (status === 'approved' || status === 'rejected') {
    auditObjList.push({
      action: `application.${status}`, resType: 'org_application', resId: oa.id, orgId: o.id,
      details: `{"action":"${status}","reviewer":"System admin"}`,
      timeStr: `${BASE_TIME} - interval '${randInt(100, 300)} days'`
    });
  }
});

// 3. period.create + period.lock / snapshot.freeze — all orgs
periodData.forEach(pd => {
  const o = orgs.find(x => x.code === pd.org);
  auditObjList.push({
    action: 'period.create', resType: 'period', resId: pd.id, orgId: o.id,
    details: `{"name":"${pd.name}","season":"${pd.s}"}`,
    timeStr: `timestamp '${pd.start}' - interval '14 days'`
  });
  if (!pd.isCur) {
    auditObjList.push({
      action: 'period.lock', resType: 'period', resId: pd.id, orgId: o.id,
      details: `{"action":"locked"}`,
      timeStr: `timestamp '${pd.start}' + interval '120 days'`
    });
  } else {
    auditObjList.push({
      action: 'snapshot.freeze', resType: 'period', resId: pd.id, orgId: o.id,
      details: `{"action":"frozen"}`,
      timeStr: `timestamp '${pd.start}' + interval '1 day'`
    });
  }
});

// 4. juror.import (batch) + juror.create (individual) — all orgs
orgs.forEach(o => {
  const curPd    = periodData.find(pd => pd.org === o.code && pd.isCur);
  if (!curPd) return;
  const orgJurors = jurorIdList.filter(j => j.org === o.code);
  auditObjList.push({
    action: 'juror.import', resType: 'juror', resId: orgJurors[0].id, orgId: o.id,
    details: `{"imported_count":${Math.min(3, orgJurors.length)},"source":"csv upload"}`,
    timeStr: `timestamp '${curPd.start}' - interval '30 days'`
  });
  orgJurors.slice(3).forEach((j, i) => {
    auditObjList.push({
      action: 'juror.create', resType: 'juror', resId: j.id, orgId: o.id,
      details: `{"juror_name":"${escapeSql(j.n.substring(0, 25))}"}`,
      timeStr: `timestamp '${curPd.start}' - interval '${28 - i} days'`
    });
  });
});

// 5. project.import — all orgs current period
orgs.forEach(o => {
  const curPd    = periodData.find(pd => pd.org === o.code && pd.isCur);
  if (!curPd) return;
  const curProjs = projList.filter(p => p.pId === curPd.id);
  auditObjList.push({
    action: 'project.import', resType: 'period', resId: curPd.id, orgId: o.id,
    details: `{"imported_count":${curProjs.length},"source":"csv upload"}`,
    timeStr: `timestamp '${curPd.start}' - interval '25 days'`
  });
});

// 6. project.create + project.update (TEDU-EE), project.delete (CMU-CS)
auditObjList.push({
  action: 'project.create', resType: 'project', resId: teduCurProjs[0].id, orgId: teduOrg.id,
  details: `{"title":"${escapeSql(teduCurProjs[0].title.substring(0, 30))}"}`,
  timeStr: `${BASE_TIME} - interval '40 days'`
});
auditObjList.push({
  action: 'project.update', resType: 'project', resId: teduCurProjs[1].id, orgId: teduOrg.id,
  details: `{"field":"title","old":"Draft Project","new":"${escapeSql(teduCurProjs[1].title.substring(0, 30))}"}`,
  timeStr: `${BASE_TIME} - interval '38 days'`
});
const cmuCurPeriod = periodData.find(pd => pd.org === 'CMU-CS' && pd.isCur);
const cmuOrg       = orgs.find(x => x.code === 'CMU-CS');
auditObjList.push({
  action: 'project.delete', resType: 'project', resId: uuid('deleted-proj-cmu'), orgId: cmuOrg.id,
  details: `{"title":"Removed Draft","reason":"duplicate entry"}`,
  timeStr: `timestamp '${cmuCurPeriod.start}' - interval '20 days'`
});

// 7. token.generate — all current-period orgs; token.revoke — TEDU-EE
periodData.filter(pd => pd.isCur).forEach((pd, i) => {
  const o = orgs.find(x => x.code === pd.org);
  auditObjList.push({
    action: 'token.generate', resType: 'entry_token', resId: uuid('tok1'+pd.id), orgId: o.id,
    details: `{"reason":"Jury session QR code"}`,
    timeStr: `timestamp '${pd.start}' - interval '${20 + i} days'`
  });
  auditObjList.push({
    action: 'token.generate', resType: 'entry_token', resId: uuid('tok2'+pd.id), orgId: o.id,
    details: `{"reason":"Backup QR code"}`,
    timeStr: `timestamp '${pd.start}' - interval '${19 + i} days'`
  });
});
auditObjList.push({
  action: 'token.revoke', resType: 'entry_token', resId: uuid('tok3'+teduCurPeriod.id), orgId: teduOrg.id,
  details: `{"reason":"manual revocation due to email leak"}`,
  timeStr: `${BASE_TIME} - interval '5 days'`
});

// 8. pin.reset — TEDU-EE, CMU-CS, TEKNOFEST
[{org: 'TEDU-EE', jIdx: 2}, {org: 'CMU-CS', jIdx: 1}, {org: 'TEKNOFEST', jIdx: 0}].forEach(({org, jIdx}) => {
  const j = jurorIdList.find(x => x.org === org && x.idx === jIdx);
  const o = orgs.find(x => x.code === org);
  auditObjList.push({
    action: 'pin.reset', resType: 'juror_period_auth', resId: j.id, orgId: o.id,
    details: `{"juror":"${escapeSql(j.n.substring(0, 25))}","reason":"forgotten pin"}`,
    timeStr: `${BASE_TIME} - interval '${15 + jIdx * 3} days'`
  });
});

// 9. juror.pin_locked + juror.edit_enabled — TEDU-EE current period
authList.filter(a => a.pId === teduCurPeriod.id).forEach((a, i) => {
  if (a.locked) {
    auditObjList.push({
      action: 'juror.pin_locked', resType: 'juror_period_auth', resId: a.jId, orgId: teduOrg.id,
      details: `{"juror":"${escapeSql(a.name)}","attempts":3,"ip":"192.168.1.10"}`,
      timeStr: `${BASE_TIME} - interval '${(i + 1) * 2} hours'`
    });
  }
  if (a.semanticState === 'Editing') {
    auditObjList.push({
      action: 'juror.edit_enabled', resType: 'juror_period_auth', resId: a.jId, orgId: teduOrg.id,
      details: `{"juror":"${escapeSql(a.name)}","reason":"Late extension request","duration_minutes":60}`,
      timeStr: `${BASE_TIME} - interval '${i + 1} hours'`
    });
  }
});

// 10. score.submit using real score_sheet IDs — TEDU-EE + CMU-CS Submitted jurors
authList
  .filter(a => (a.org === 'TEDU-EE' || a.org === 'CMU-CS') && a.semanticState === 'Completed' && a.isCur)
  .slice(0, 8)
  .forEach((a, i) => {
    const o = orgs.find(x => x.code === a.org);
    const myProjs = projList.filter(p => p.pId === a.pId);
    myProjs.slice(0, 2).forEach(proj => {
      const ssId = uuid(`ss-${a.jId}-${proj.id}`);
      auditObjList.push({
        action: 'score.submit', resType: 'score_sheet', resId: ssId, orgId: o.id,
        details: `{"juror_activity":"finalized"}`,
        timeStr: `${BASE_TIME} - interval '${(i + 1) * 3} hours'`
      });
    });
  });

// 11. score.update using real score_sheet IDs — Editing jurors
authList
  .filter(a => a.semanticState === 'Editing')
  .slice(0, 3)
  .forEach((a, i) => {
    const o = orgs.find(x => x.code === a.org);
    const myProjs = projList.filter(p => p.pId === a.pId);
    if (myProjs[0]) {
      const ssId = uuid(`ss-${a.jId}-${myProjs[0].id}`);
      auditObjList.push({
        action: 'score.update', resType: 'score_sheet', resId: ssId, orgId: o.id,
        details: `{"corrections":2,"reason":"edit window granted"}`,
        timeStr: `${BASE_TIME} - interval '${(i + 1) * 2} hours'`
      });
    }
  });

auditObjList.forEach(ad => {
  const aId = uuid(`audit-log-${ad.action}-${ad.resId}-${ad.timeStr}`);
  out.push(`INSERT INTO audit_logs (id, organization_id, user_id, action, resource_type, resource_id, details, created_at) VALUES ('${aId}', '${ad.orgId}', NULL, '${ad.action}', '${ad.resType}', '${ad.resId}', '${escapeSql(ad.details)}', ${ad.timeStr}) ON CONFLICT DO NOTHING;`);
});

out.push('');

// JURY FEEDBACK
out.push(`-- Jury Feedback`);
const juryFeedbackData = [
  // TEDU-EE
  { pSeed: 'period-TEDU-EE-0',     jSeed: 'juror-TEDU-EE-0',      rating: 4, comment: null,                                                                                             pub: false },
  // IEEE
  { pSeed: 'period-IEEE-APSSDC-0', jSeed: 'juror-IEEE-APSSDC-0',  rating: 5, comment: 'Incredibly smooth experience. Scored 12 projects in under an hour with no hiccups.',             pub: true  },
  { pSeed: 'period-IEEE-APSSDC-0', jSeed: 'juror-IEEE-APSSDC-1',  rating: 4, comment: 'Clean interface, very intuitive. Would love a dark mode option on the scoring screen.',          pub: true  },
  { pSeed: 'period-IEEE-APSSDC-0', jSeed: 'juror-IEEE-APSSDC-2',  rating: 5, comment: 'Best evaluation tool I have used for conference paper reviews. Simple yet powerful.',            pub: true  },
  { pSeed: 'period-IEEE-APSSDC-1', jSeed: 'juror-IEEE-APSSDC-0',  rating: 5, comment: null,                                                                                             pub: false },
  { pSeed: 'period-IEEE-APSSDC-1', jSeed: 'juror-IEEE-APSSDC-1',  rating: 4, comment: null,                                                                                             pub: false },
  { pSeed: 'period-IEEE-APSSDC-1', jSeed: 'juror-IEEE-APSSDC-2',  rating: 5, comment: 'Used VERA again for the second time — consistently excellent.',                                  pub: true  },
  // CanSat
  { pSeed: 'period-CANSAT-2025-0', jSeed: 'juror-CANSAT-2025-0',  rating: 5, comment: 'We evaluated 24 CanSat teams in a single afternoon. Real-time rankings kept the event exciting.', pub: true  },
  { pSeed: 'period-CANSAT-2025-0', jSeed: 'juror-CANSAT-2025-1',  rating: 4, comment: 'Great for competition settings. The rubric sheet was very helpful.',                             pub: true  },
  { pSeed: 'period-CANSAT-2025-0', jSeed: 'juror-CANSAT-2025-2',  rating: 5, comment: null,                                                                                             pub: false },
  { pSeed: 'period-CANSAT-2025-1', jSeed: 'juror-CANSAT-2025-0',  rating: 4, comment: null,                                                                                             pub: false },
  { pSeed: 'period-CANSAT-2025-1', jSeed: 'juror-CANSAT-2025-1',  rating: 5, comment: 'Even better than last year. The admin panel gives instant insight into scoring patterns.',       pub: true  },
  { pSeed: 'period-CANSAT-2025-1', jSeed: 'juror-CANSAT-2025-2',  rating: 4, comment: 'Straightforward and efficient. No training needed — I just started scoring.',                   pub: true  },
  // CMU
  { pSeed: 'period-CMU-CS-0',      jSeed: 'juror-CMU-CS-0',       rating: 5, comment: 'Replaced our old paper-based system entirely. The export feature alone saves hours of work.',   pub: true  },
  { pSeed: 'period-CMU-CS-0',      jSeed: 'juror-CMU-CS-1',       rating: 4, comment: 'Solid tool. The configurable criteria made it easy to adapt to our CS capstone format.',        pub: true  },
  { pSeed: 'period-CMU-CS-1',      jSeed: 'juror-CMU-CS-0',       rating: 5, comment: null,                                                                                             pub: false },
  { pSeed: 'period-CMU-CS-1',      jSeed: 'juror-CMU-CS-1',       rating: 3, comment: null,                                                                                             pub: false },
  { pSeed: 'period-CMU-CS-2',      jSeed: 'juror-CMU-CS-0',       rating: 4, comment: null,                                                                                             pub: false },
  { pSeed: 'period-CMU-CS-2',      jSeed: 'juror-CMU-CS-1',       rating: 5, comment: 'Third semester using VERA. It keeps getting better.',                                            pub: true  },
  // TEKNOFEST
  { pSeed: 'period-TEKNOFEST-0',   jSeed: 'juror-TEKNOFEST-0',    rating: 5, comment: 'Yüzlerce takımı hızlıca değerlendirdik. Sistem çok stabil ve hızlıydı.',                        pub: true  },
  { pSeed: 'period-TEKNOFEST-1',   jSeed: 'juror-TEKNOFEST-0',    rating: 4, comment: null,                                                                                             pub: false },
  { pSeed: 'period-TEKNOFEST-1',   jSeed: 'juror-TEKNOFEST-1',    rating: 5, comment: 'Kullanımı çok kolay, eğitim bile gerekmedi. Tüm jüri arkadaşlarım memnun kaldı.',               pub: true  },
  // CanSat third
  { pSeed: 'period-CANSAT-2025-2', jSeed: 'juror-CANSAT-2025-1',  rating: 3, comment: null,                                                                                             pub: false },
  { pSeed: 'period-CANSAT-2025-2', jSeed: 'juror-CANSAT-2025-2',  rating: 5, comment: null,                                                                                             pub: false },
];

const feedbackRows = juryFeedbackData.map(f => {
  const pId = uuid(f.pSeed);
  const jId = uuid(f.jSeed);
  const comment = f.comment ? `'${escapeSql(f.comment)}'` : 'NULL';
  return `('${pId}', '${jId}', ${f.rating}, ${comment}, ${f.pub})`;
});

out.push(`INSERT INTO jury_feedback (period_id, juror_id, rating, comment, is_public) VALUES\n${feedbackRows.join(',\n')}\nON CONFLICT (period_id, juror_id) DO NOTHING;`);
out.push('');

out.push(`COMMIT;\n`);

fs.writeFileSync(path.resolve(__dirname, '../sql/seeds/demo_seed.sql'), out.join('\n'));
console.log('Demo seed written to sql/seeds/demo_seed.sql');
