// src/shared/api/index.js
// Public API surface — re-exports all modules.

export { withRetry } from "./core/retry";
export { supabase } from "./core/client";
export { dbScoresToUi, uiScoresToDb, dbAvgScoresToUi, formatMembers } from "./fieldMapping";

export {
  authenticateJuror,
  verifyJurorPin,
  verifyEntryToken,
  upsertScore,
  getJurorById,
  listProjects,
  getJurorEditState,
  finalizeJurorSubmission,
  listPeriods as listPeriodsPublic,
  getCurrentPeriod,
  freezePeriodSnapshot,
  listProjectsWithRetry,
  upsertScoreWithRetry,
  listSemesters,
  getCurrentSemester,
} from "./juryApi";

export {
  getSession,
  listOrganizationsPublic,
  submitApplication,
  getMyApplications,
  cancelApplication,
  approveApplication,
  rejectApplication,
  listPendingApplications,
  listPeriods,
  setCurrentPeriod,
  createPeriod,
  updatePeriod,
  deletePeriod,
  setEvalLock,
  updatePeriodCriteriaConfig,
  updatePeriodOutcomeConfig,
  adminListProjects,
  createProject,
  upsertProject,
  deleteProject,
  createJuror,
  updateJuror,
  deleteJuror,
  resetJurorPin,
  setJurorEditMode,
  forceCloseJurorEditMode,
  listLockedJurors,
  unlockJurorPin,
  listOrganizations,
  createOrganization,
  updateOrganization,
  updateMemberAdmin,
  deleteMemberHard,
  getScores,
  listJurorsSummary,
  getProjectSummary,
  getOutcomeTrends,
  getOutcomeAttainmentTrends,
  getDeleteCounts,
  deleteEntity,
  listPeriodCriteria,
  listPeriodOutcomes,
  generateEntryToken,
  revokeEntryToken,
  getEntryTokenStatus,
  listAuditLogs,
  fullExport,
  upsertProfile,
  getProfile,
  listFrameworks,
  createFramework,
  updateFramework,
  deleteFramework,
  listOutcomes,
  createOutcome,
  updateOutcome,
  deleteOutcome,
  listCriterionOutcomeMappings,
  upsertCriterionOutcomeMapping,
  deleteCriterionOutcomeMapping,
  sendEntryTokenEmail,
  sendJurorPinEmail,
  sendExportReport,
  getMaintenanceStatus,
  getMaintenanceConfig,
  setMaintenance,
  cancelMaintenance,
  getSecurityPolicy,
  setSecurityPolicy,
} from "./admin/index";
